### ISSUE TITLE
Possible to use expose with Valet secure?

### ISSUE THREAD

**Issue by mpemburn** [beyondcode/expose#100]
Hi,

Wonderful app!  I was able to get to work in minutes with a test project using Valet+ with:

`expose share http://roster.test`

After running `valet secure`, though, I get the message: 

Valet could not find directory **roster.test:443**

Is there a way around this?  All of my dev sites need to use https.

Thanks!

Mark Pemburn
Blue Ocean Ideas

**Comment by Cazzar** [comment]
If you use `expose share https://roster.test` in your case, it should work fine I've used it before using a `valet secure`'d app, though I am only using valet, not valet+

**Comment by mpemburn** [comment]
@Cazzar — thanks, but that's what I did as well.  The issue is that it adds :443 to the end of the URL that's it's trying to resolve locally, and Valet doesn't know what to do with that.

**Comment by josegus** [comment]
@Cazzar for me is working fine when I run:

expose share https://myapp.test

But is not working when running:

(root of my app) expose 

I have used valet park on a folder called /home/Sites. Maybe you need to link individually each site you have with valet
