### ISSUE TITLE
Is it possible to host other tcp port?

### ISSUE THREAD

**Issue by heythisisvivek** [beyondcode/expose#101]
In ngrok we can easily host other TCP port such ssh 22, I tried same thing in expose it ask for authentication message of yes/no after hitting yes it stuck and in few minute Connection close by xxx.xx.xx.xx by port 22 come up. So can we host other tcp port on expose?

**Comment by mpociot** [comment]
No, expose currently can only share the HTTP protocol and not tunnel random ports. Even though that would be a great addition.
