### ISSUE TITLE
Documentation contribution: Example Expose Apache Proxy configuration

### ISSUE THREAD

**Issue by CDRO** [beyondcode/expose#102]
Hi there

I built an apache reverse proxy for my server and thought I'd share the configuration.

Somehow I needed to use two configurations, one for my registration domain and one for the wildcard configuration.

This is the wildcard configuration but it can easily be adapted to the non-wildcard one by removing the `ServerAlias`:
```
<IfModule mod_ssl.c>
<VirtualHost *:443>
	ServerName expose.domain.tld
	ServerAlias *.expose.domain.tld
	LoadModule        proxy_module            modules/mod_proxy.so
	LoadModule        proxy_http_module       modules/mod_proxy_http.so

        ServerAdmin admin@domain.tld

	ProxyPass "/" "http://localhost:8080/"
	ProxyPassReverse "/" "http://localhost:8080/"
	ProxyPreserveHost On
	

        # Needed for websocket support
        RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC,OR]
        RewriteCond %{HTTP:CONNECTION} ^Upgrade$ [NC]
        RewriteRule .* ws://127.0.0.1:8080%{REQUEST_URI} [P,QSA,L]

	<Proxy http://localhost:8080>

		Require all granted

		Options none
	</Proxy>

        ErrorLog ${APACHE_LOG_DIR}/expose.domain.tld-error.log
        CustomLog ${APACHE_LOG_DIR}/expose.domain.tld-access.log combined

        SSLCertificateFile /etc/letsencrypt/live/expose.domain.tld-0001/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/expose.domain.tld-0001/privkey.pem
        Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
```

This works with expose started in the cli or with `supervisor` (as suggested in the existing doc).

Best Regards

**Comment by dennisong45** [comment]
> Hi there
> 
> I built an apache reverse proxy for my server and thought I'd share the configuration.
> 
> Somehow I needed to use two configurations, one for my registration domain and one for the wildcard configuration.
> 
> This is the wildcard configuration but it can easily be adapted to the non-wildcard one by removing the `ServerAlias`:
> 
> ```
> <IfModule mod_ssl.c>
> <VirtualHost *:443>
> 	ServerName expose.domain.tld
> 	ServerAlias *.expose.domain.tld
> 	LoadModule        proxy_module            modules/mod_proxy.so
> 	LoadModule        proxy_http_module       modules/mod_proxy_http.so
> 
>         ServerAdmin admin@domain.tld
> 
> 	ProxyPass "/" "http://localhost:8080/"
> 	ProxyPassReverse "/" "http://localhost:8080/"
> 	ProxyPreserveHost On
> 	
> 
>         # Needed for websocket support
>         RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC,OR]
>         RewriteCond %{HTTP:CONNECTION} ^Upgrade$ [NC]
>         RewriteRule .* ws://127.0.0.1:8080%{REQUEST_URI} [P,QSA,L]
> 
> 	<Proxy http://localhost:8080>
> 
> 		Require all granted
> 
> 		Options none
> 	</Proxy>
> 
>         ErrorLog ${APACHE_LOG_DIR}/expose.domain.tld-error.log
>         CustomLog ${APACHE_LOG_DIR}/expose.domain.tld-access.log combined
> 
>         SSLCertificateFile /etc/letsencrypt/live/expose.domain.tld-0001/fullchain.pem
>         SSLCertificateKeyFile /etc/letsencrypt/live/expose.domain.tld-0001/privkey.pem
>         Include /etc/letsencrypt/options-ssl-apache.conf
> </VirtualHost>
> </IfModule>
> ```
> 
> This works with expose started in the cli or with `supervisor` (as suggested in the existing doc).
> 
> Best Regards

Hi Quick question. Do you create a new *.com-le-ssf.conf file for this wildcard proxy?

**Comment by CDRO** [comment]
Hi,

this *is* indeed the *.com-le-ssl.conf that you'll need. You can also generate a normal configuration for your webhost and then create everything with letsencrypt and extend with the parts regarding `ProxyPass`, `ProxyPassReverse` and the `RewriteCond/Rule` (these are necessary as apache has no way to handle Websockets yet).

I hope this clarifies your question.

**Comment by dennisong45** [comment]
Thank you for your reply. I will assume these are the following steps.

1) Add wildcard SSL cert using Certbot in apache server.
2) From DNS Domain Side add wildcard configuration as well following certbot instructions.
3) Create ` *.com-le-ssl.conf `

For .conf file

in the server name do we need to add 
ServerName `expose.domain.tld`
ServerAlias `*.expose.domain.tld`

the word `expose` infront of our domain?

eg: usually i start expose tunnel client with subdomain the url will be just `abc.mydomain.com`

**Comment by CDRO** [comment]
Exactly, these would be the steps to follow.

You don't _need_ to have the ServerName expose.domain.tld, it can be anything (I for myself used `share` as subdomain), but this "main"-subdomain will allow you to access the main page to check if it works.

Then, on the side of your web application, you can simply call: `expose share http://localhost --subdomain=mydubdomain.expose.domain.tld` (or anything else, if you wish).

**Comment by dennisong45** [comment]
Thank you for your reply.

I'm not sure what i'm doing wrong. 

`
<IfModule mod_ssl.c>
<VirtualHost *:443>

        ServerName expose
        ServerAlias *.expose

        LoadModule        proxy_module            modules/mod_proxy.so
        LoadModule        proxy_http_module       modules/mod_proxy_http.so


        ServerAdmin me@mydomain.com

        ProxyPass "/" "http://localhost:8080/"
        ProxyPassReverse "/" "http://localhost:8080/"
        ProxyPreserveHost On


    # Needed for websocket support
    RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC,OR]
    RewriteCond %{HTTP:CONNECTION} ^Upgrade$ [NC]
    RewriteRule .* ws://127.0.0.1:8080%{REQUEST_URI} [P,QSA,L]

        <Proxy http://localhost:8080>

                Require all granted

                Options none
        </Proxy>

    DocumentRoot /var/www/html/mydomain.com/public_html
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
        Include /etc/letsencrypt/options-ssl-apache.conf
        SSLCertificateFile /etc/letsencrypt/live/mydomain.com/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/mydomain.com/privkey.pem

</VirtualHost>
</IfModule>

`
`
sudo php expose share http://127.0.0.1/plexus --subdomain=hello.expose
`
Link Generated

`
Expose-URL:             http://hello.expose.mydomain.com:8080
`

Still goes to Http, and https:// manually wont' work. Any tips ? thank you for your time.

**Comment by CDRO** [comment]
If I understand correctly, expose tells you, that it exposed your site to `http://hello.expose.mydomain.com:8080`, are you then trying to access it using this url or what url do you access it exactly?

From my understanding, seeing your configuration, you should be having a hosts record (or an internal DNS record) for hello.expose, so as you can access https://hello.expose/ (which is then mapped by apache through the proxy on port `8080`).

**Comment by dennisong45** [comment]
Hi thank you for helping me.

I used this command `sudo php expose share http://127.0.0.1/plexus --subdomain=hello.expose`
so expose generated `http://hello.expose.mydomain.com:8080` like what you said.

On the DNS record i followed the certbot and certified the certificate by adding CNAME TXT Record verification.
Do i still need to add an additional HOST record?

**Comment by CDRO** [comment]
I'm not sure how this works with CNAMEs but I guess, as long as you open `https://hello.expose.mydomain.com` everything should work as expected.

On my setup, I used a wildcard A-record like `*.expose.mydomain.com`, I'm not sure if this has any consequences but I guess it should not.
