### ISSUE TITLE
Cannot view expose Dashboard

### ISSUE THREAD

**Issue by ashwinsingh1089** [beyondcode/expose#105]
Hi, I keep getting a 413 error whenever I try to access expose dashboard at **http://127.0.0.1:4040**. Not sure what's the issue here as I am able to spin up local server using the command, **expose share localhost:8080 --subdomain=subdomain** . Any advice would be appreciated. thanks!

**Comment by mpociot** [comment]
Can you run `curl localhost:4040` and paste the output?
Maybe another process is already running on port 4040?

**Comment by Shabinder** [comment]
I am also getting a blank page when going to localhost:4040
and curl localhost:4040
give no output too.

**Comment by mark-apn** [comment]
Ive got the same error, but in a different place. Im trying to set up my personal domain on a raspberry pi

Serve command:
> 
> pi@raspberrypi:~ $ expose serve -vvv nicepants.dev
> 
> Box Requirements Checker
> ========================
> 
> > Using PHP 7.3.19-1~deb10u1
> > PHP is using the following php.ini file:
>   /etc/php/7.3/cli/php.ini
> 
> > Checking Box requirements:
>   ✔ The application requires the version "^7.3.0" or greater.
>   ✔ The application requires the extension "zlib".
>   ✔ The application requires the extension "json".
>   ✔ The package "composer/ca-bundle" requires the extension "openssl".
>   ✔ The package "padraic/humbug_get_contents" requires the extension "openssl".
>   ✔ The package "composer/ca-bundle" requires the extension "pcre".
> 
> 
>  [OK] Your system is ready to run the application.
> 
> 
> Expose server running on port 8080.

It reaches my nginx proxy but after that im getting a 413 via the browser. A local cURL also results in a 413

```
pi@raspberrypi:/etc/nginx/sites-enabled $ curl -vvv 127.0.0.1:8080
* Expire in 0 ms for 6 (transfer 0x265880)
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x265880)
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.64.0
> Accept: */*
>
< HTTP/1.1 413 Request Entity Too Large
< X-Powered-By: Ratchet/0.4.1
* no chunk, no close, no size. Assume close to signal end
```

**Comment by mark-apn** [comment]
@mpociot Anything I can do for you that will make it easier to pinpoint the problem? Would love to help :-)

**Comment by taimaiduc** [comment]
I have the same error as well
Curl 8080 is always 413 error

**Comment by taimaiduc** [comment]
Up for 2 years 😄

**Comment by sschlein** [comment]
Closing this issue because it's stale. Please feel free to open a new one if it's still relevant.
