### ISSUE TITLE
how to use expose behind corporate proxy?

### ISSUE THREAD

**Issue by mayurgoenka** [beyondcode/expose#109]
expose share http://localhost:4040
Could not connect to the server.
Connection to tls://sharedwithexpose.com:443 timed out after 20 seconds

this is happening because i am behind corporate proxy.

**Comment by mpociot** [comment]
Proxies are not yet supported. I’ll see if I can add it for an upcoming release.

**Comment by ybenitezf** [comment]
Is there an update on this ?

**Comment by zombieleet** [comment]
this is still a problem
