### ISSUE TITLE
Expose Link Not Working

### ISSUE THREAD

**Issue by dennisong45** [beyondcode/expose#111]
After running expose on /var/www/html/mysite

```
------
Local-URL:              mysite.test
Dashboard-URL:          http://127.0.0.1:4040
Expose-URL:             https://mysite.sharedwithexpose.com

+--------+-----+----------+---------------------+----------+
| Method | URI | Response | Time                | Duration |
+--------+-----+----------+---------------------+----------+
| GET    | /   |          | 2020-08-25 16:59:43 | 0ms      |
| GET    | /   |          | 2020-08-25 16:59:39 | 3676ms   |
| GET    | /   |          | 2020-08-25 16:44:14 | 928731ms
```

Tried : expose share http://127.0.0.1:8000 as well
Same error.
Dashboard site can't be reached
Expose URL Constantly Waiting as well.

PHP 7.4.3 Apache Server

**Comment by MHassanSaqib** [comment]
Any solution?

**Comment by dennisong45** [comment]
> Any solution?

Try this : 

`expose share http://127.0.0.1/myWebFolder --subdomain=dennis`

**Comment by MHassanSaqib** [comment]
> > Any solution?
> 
> Try this :
> 
> `expose share http://127.0.0.1/myWebFolder --subdomain=dennis`

I tried that too. I am using quasar framework and serving it on port 8080 in dev mode.  Also tried it for pure vuejs project but same results.
