### ISSUE TITLE
Automate /.config/.expose file?

### ISSUE THREAD

**Issue by dennisong45** [beyondcode/expose#113]
Is it possible to automate ~/.config/.expose file so that the host URL is : always point to my-domain.com Instead of beyondcode everytime i install expose?

**Comment by mpociot** [comment]
Since the config file gets copied from the installation command, this is only possible if you would fork Expose and modify the default stub file.

**Comment by dennisong45** [comment]
How do i edit the stub file? can you point me towards the direction. Thank you.
