### ISSUE TITLE
How to generate an auth token?

### ISSUE THREAD

**Issue by CoffeeKing68** [beyondcode/expose#114]
Hi

The documentation says that I need to create an account and sign in, but whats the next step?
Sorry if its obvious :)

Thanks
CoffeeKing68

**Comment by aginev** [comment]
After you are logged in you are redirected to your dashboard where all of your courses and licenses are listed. Find Expose and click at "Licenses & Download" button. Just below the instalation instructions there is

```
My auth token
Use this authentication token to connect to our expose server.
You can set the token using:
expose token XXXX-XXXX-XXXX
```

Regards

Nasko

**Comment by CoffeeKing68** [comment]
Ok I see it here https://beyondco.de/licenses.
Don't know why I didn't see it the first time.

Thanks for the help
CoffeeKing68

**Comment by e10a** [comment]
Now it's found here [https://beyondco.de/licenses/expose](https://beyondco.de/licenses/expose)
