### ISSUE TITLE
Protocol error on images

### ISSUE THREAD

**Issue by iantearle** [beyondcode/expose#116]
Ok, so this may be an edge case with SLIR image caching, but I am getting at random with images generated by SLIR Image protocol errors:

```The operation couldn’t be completed. Protocol error```

https://github.com/lencioni/SLIR 

Summary of the image looks like this in console:

```
URL: https://**.sharedwithexpose.com/expanse/images/h150/a150_060.JPG
Status: —
Source: —
Initiator: 
**.sharedwithexpose.com:58
```

If I visit the image directly, it renders correctly without any errors, this seems to be only when multiple images are generated/fetched at a time - on the home page only 12. If I visit the site on the local domain without using expose I do not see this error.

**Comment by mpociot** [comment]
Could you provide an example tunnel/website?
Also, which version of PHP and which OS are you using to share your site?

**Comment by iantearle** [comment]
https://aa.sharedwithexpose.com

PHP 7.2

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15

**Comment by mpociot** [comment]
I couldn't reproduce the issue. If it still exists, feel free to reopen the issue.
