### ISSUE TITLE
--subdomain option does not work with basic expose command 

### ISSUE THREAD

**Issue by Artessan** [beyondcode/expose#12]
I think that running 
```
expose --subdmain=bar
```
 in foo folder should set the basic config and use the custom given 
```https://bar.sharedwithexpose.com/```
 domain but rigth the share domain is  
```https://foo.sharedwithexpose.com/```

iis this a bug or it's planned to works in that way???

**Comment by mpociot** [comment]
Yeah right, that doesn't work at the moment, but having a subdomain option here is a good idea.

**Comment by drakakisgeo** [comment]
Not sure if its the same thing but my case was that a Laravel project can listen app.mydomain.test , mydomain.test, api.mydomain.test.   How can I point "mydomain.sharedwithexpose.com" to my local api.mydomain.test ? 

Subdomain didn't do the trick for me.
