### ISSUE TITLE
Accessing Expose-URL only results in 301 Moved Permanently

### ISSUE THREAD

**Issue by axit-joost** [beyondcode/expose#13]
| Library | Version |
|---|---|
| Expose | 1.0.1 |
| Laravel | 7.16.1 
| PHP | 7.4.6 |
| Platform| Mac |

1. Used Tighten's [Lambo](https://github.com/tightenco/lambo) to new up a project, e.g. `lambo hotnewsite`.
2. Ran `expose`
3. Accessed the Expose-URL from iPhone

```sh
❯ expose
Thank you for using Expose!

⭐️ Support us by starring the repo at https://github.com/beyondcode/expose ⭐️
---
Local-URL:		hotnewsite.test
Dashboard-URL:		http://127.0.0.1:4040
Expose-URL:		https://hotnewsite.sharedwithexpose.com

+--------+-----+-----------------------+----------+
| Method | URI | Response              | Duration |
+--------+-----+-----------------------+----------+
| GET    | /   | 301 Moved Permanently | 5ms      |
| GET    | /   | 301 Moved Permanently | 30ms     |
+--------+-----+-----------------------+----------+
```

It redirects to `https://hotnewsite.test`

Notes:
- I host locally using Laravel Valet.
- The site is secured by Lambo through Laravel Valet (I believe Lambo issues a `valet secure`).

**Comment by axit-joost** [comment]
I think it's `valet secure` that is messing things up. If I issue a `valet unsecure` which removes the TLS certificate, and rerun expose, it will work just fine.

**Comment by mpociot** [comment]
Right now, expose is unable to automatically detect if the site you want to share is secured via Valet.
To tunnel traffic to secured local sites, you need to explicitly share the HTTPS URL:

```
expose share https://hotnewsite.test
```
