### ISSUE TITLE
On Premise Server Auth Token

### ISSUE THREAD

**Issue by bsayiner** [beyondcode/expose#133]
Hello.
I'm trying to create auth-token for the server-side. Because I don't want to allow connection without validating tokens. But I cannot find how to define auth token. I know that client-side user auth-token configuration from config.php

But I cannot found how to define auth-token on the server-side

**Comment by michellaurent** [comment]
Simply visit your expose URL (expose.yourdomain.com) and click on the user tab to create new users.

**Comment by mpociot** [comment]
Or you can use the expose users API 

https://beyondco.de/docs/expose/api/users#creating-a-new-user
