### ISSUE TITLE
Issues using with Homestead

### ISSUE THREAD

**Issue by Braunson** [beyondcode/expose#136]
I've tried using this inside and outside of Laravel Homestead with issues. Expose does give me a expose-url and shows the initial connection (when I visit the expose-url) but it never ever loads, it just sits there loading a blank page forever until it times out.

Any ideas what's going on?

**Comment by dennisong45** [comment]
I had this same problem when using the terminal command ```expose``` only.

I used ```expose share http://127.0.0.1/``` and then it works.

**Comment by Braunson** [comment]
@dennisong45 That does not work for me inside and outside of Homestead.

**Comment by dennisong45** [comment]
What error did you get? just hang?

**Comment by Braunson** [comment]
@dennisong45 Depending if it's inside or outside, it's a 404 or Forbidden.

**Comment by mpociot** [comment]
@Braunson you should use expose from outside the VM. So you should just be able to call

expose share http://your-site.test

**Comment by Braunson** [comment]
@mpociot I tried that but when I try to go to the provided Expose-URL I get `403 Forbidden`. I'm using the latest Homestead.

**Comment by mpociot** [comment]
Do you see the request in the expose dashboard? Do the headers look good?

**Comment by Braunson** [comment]
@mpociot Yes I see the request in the dashboard and the proper headers.

Here is the headers

```
$headers = [
    'Host' => 'project.local', // Changed to hide client's name
    'x-forwarded-for' => '173.238.188.50',
    'x-forwarded-proto' => 'https',
    'Connection' => 'upgrade',
    'upgrade-insecure-requests' => '1',
    'dnt' => '1',
    'User-Agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36',
    'Accept' => 'text/html, application/xhtml+xml, application/xml;q=0.9, image/avif, image/webp, image/apng, */*;q=0.8, application/signed-exchange;v=b3;q=0.9',
    'sec-fetch-site' => 'cross-site',
    'sec-fetch-mode' => 'navigate',
    'sec-fetch-user' => '?1',
    'sec-fetch-dest' => 'document',
    'Referer' => 'http://127.0.0.1:4041/',
    'Accept-Language' => 'en-US, en;q=0.9',
    'Accept-Encoding' => 'br, gzip, deflate',
    'x-expose-request-id' => '5f67a11013420',
    'x-exposed-by' => 'Expose unreleased',
    'x-original-host' => 'pcqrs6u5wy.sharedwithexpose.com',
];
```

Here's the response data
```
Headers

Date Sun, 20 Sep 2020 18:36:01 GMT
Server Apache/2.4.29 (Ubuntu)
Content-Length 280
Content-Type text/html; charset=iso-8859-1
Response Raw

Preview

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.29 (Ubuntu) Server at project.local Port 80</address>
</body></html>
```

**Comment by Braunson** [comment]
Removing and reinstalling Expose resolved the issue, weird. Thanks.
