### ISSUE TITLE
Config File maintain the same after repackaging it.

### ISSUE THREAD

**Issue by dennisong45** [beyondcode/expose#137]
Does anyone try forking it and rebuilding it and package it to packagist.org?
I'm trying to deploy expose to all my client machines. I edit the``` expose/config/expose.php```
and change the default server pointing towards the client host. and then add push commit to my forked repo and repackage it to packagist. 

The thing is after download my custom package, the config remains the same after building it. 
Where should I edit the build? Any tips will appreciate it.

**Comment by sschlein** [comment]
Closing this issue because it's old. Please feel free to open a new one if it's still relevant.
