### ISSUE TITLE
Expose throws error on Windows when running the 'expose token' command

### ISSUE THREAD

**Issue by fsavalam** [beyondcode/expose#14]
I tried to set my authentication token on windows by running 
`expose token sUpEr-AwEsOmE-fAkE-tOkEn`

but it throws an error 

`In StoreAuthenticationTokenCommand.php line 27: `
  `Undefined index: HOME`

![ff](https://user-images.githubusercontent.com/15837064/84897573-6cb4d100-b06b-11ea-9c7a-d15736608446.PNG)

bug maybe?

**Comment by parmindermca84** [comment]
For windows, it needs to be used combination of `$_SERVER['HOMEDRIVE']` and `$_SERVER['HOMEPATH']`

**Comment by fsavalam** [comment]
> For windows, it needs to be used combination of `$_SERVER['HOMEDRIVE']` and `$_SERVER['HOMEPATH']`

What do you mean exactly?

**Comment by randohinn** [comment]
This also happens when using any other expose command, just in different places.. 

``` 
C:\Magic\BlackMagic> expose

In ShareCurrentWorkingDirectoryCommand.php line 22:

  Undefined index: HOME  

```

**Comment by innocenzi** [comment]
On Windows, the `USERPROFILE` environment variable contains the path to the current user directory. So it should become `$_SERVER['HOME'] ?? $_SERVER['USERPROFILE']`.

**Comment by sohaibilyas** [comment]
got same error on CMD but worked find using gitbash terminal or wsl

**Comment by fsavalam** [comment]
> got same error on CMD but worked find using gitbash terminal or wsl

Same here...

**Comment by abhiburk** [comment]
Tried using GitBash but still not working. Even using $_SERVER['HOME'] ?? $_SERVER['USERPROFILE'] it is throwing me the same error
