### ISSUE TITLE
Using multiple config file

### ISSUE THREAD

**Issue by RogerSik** [beyondcode/expose#141]
Hello,

is it possible to use multiple different config files? Example: we want one config file for the public expose server and a different file for the internal expose server.

Currently we are changing multiple times "host" setting. This as an argument (--host=example.org or --config-path=/xxx/ example) would be nice. The tokens in our scenario are shared between the 2 server.

**Comment by mpociot** [comment]
Expose is looking for a local config file in the current working directory, before using the global config file. So you can just place a .expose.php file in the folder(s) where you need a custom config 

See https://github.com/beyondcode/expose/blob/master/app/Providers/AppServiceProvider.php#L40
