### ISSUE TITLE
Abusive on Facebook

### ISSUE THREAD

**Issue by dostrog** [beyondcode/expose#143]
Whilst develop BOT for Facebook Messenger I used to NGROK. Have tried Expose for tunnelling and got error from FB when try to set persistent_menu with URL pointing to any subdomain generated by Expose. This is error message:

"Something went wrong: Your message couldn't be sent because it includes content that other people on Facebook have reported as abusive." 

Content does not change. Everything is OK with NGROK but not with tunnelling via Expose.

Is it possible to avoid this?

**Comment by mpociot** [comment]
I tried getting in touch with Facebook about this to whitelist the expose domain. Let's see what happens

**Comment by dostrog** [comment]
Try to connect through Expose to localhost from Facebook today and it's worked.
Waiting for Expose Pro….
