### ISSUE TITLE
laravel dependency

### ISSUE THREAD

**Issue by Fuseteam** [beyondcode/expose#144]
i installed expose by running  `composer global require beyondcode/expose`
then i cd into my project and run expose with
`~/.composer/vendor/beyondcode/expose/expose`
i get the following  error:
`PHP Fatal error:  Uncaught Error: Class 'LaravelZero\Framework\Application' not found in /home/tk/.composer/vendor/beyondcode/expose/bootstrap/app.php:14
Stack trace:
#0 /home/tk/.composer/vendor/beyondcode/expose/expose(30): require_once()
#1 {main}
  thrown in /home/tk/.composer/vendor/beyondcode/expose/bootstrap/app.php on line 14`

**Comment by TiiFuchs** [comment]
Try running it by calling `~/.composer/vendor/bin/expose`
Does that change anything?

**Comment by Fuseteam** [comment]
@TiiFuchs that indeed runs it thanks!
