### ISSUE TITLE
Can't reach expose.mydomain.com

### ISSUE THREAD

**Issue by goellner** [beyondcode/expose#15]
I'm currently trying to get expose running with a custom domain. First of all, I had PHP 7.2 installed and ran into some errors while trying to run the "expose serve" command. There are no server requirements listed in the documentation. I switched to 7.3 and it works now.

I've successfully started the server and added it to supervisord (running on Laravel Forge). I have setup SSL and the reverse proxy. I can see an expose landing page on mydomain.com, but can't reach expose.mydomain.com. Do I have to add something to the nginx configuration to get this up and running?

What are the recommended DNS settings for running your own expose server? I have a wildcard ssl with route53 setup in laravel forge, I guess thats the correct way. 

Further: I've run `expose publish` to have a file to edit on the server, where I can set username and password for the admin interface. Couldn't find anything about this in the docs either.

**Comment by mpociot** [comment]
Have you set up your server as a wildcard domain on Forge as well? That’s how I’m using it too. 
Maybe you can share your nginx configuration?

Regarding the documentation: it’s part of this repo, so any PRs with things you’ve encountered would be appreciated

**Comment by goellner** [comment]
Okay, that helped, I forgot to tick `Allow Wildcard Sub-Domains`, now I can reach expose.mydomain.com. It seems to ignore the username & password I set i n the `/home/forge/.expose/config.php` file though. I changed the credentials, ran `supervisorctl restart expose`, but I can still only login with the default `username` and `password`.

Is it correct that I have to run `expose publish` to get the config file for the server?

**Comment by mpociot** [comment]
Hm..could you try placing the config file as `.expose.php` in the working directory of your expose server?
That's the second location that expose is looking up the configuration file.

See: https://github.com/beyondcode/expose/blob/master/app/Providers/AppServiceProvider.php#L34-L57

**Comment by filipac** [comment]
What worked for me now: ```ln -s .expose/config.php .expose.php``` in /home/forge as that is the working directory for supervisord

**Comment by goellner** [comment]
> Hm..could you try placing the config file as `.expose.php` in the working directory of your expose server?
> That's the second location that expose is looking up the configuration file.
> 
> See: https://github.com/beyondcode/expose/blob/master/app/Providers/AppServiceProvider.php#L34-L57

That didn't change anything. I guess its what @filipac said about the supervisord and its working directory. It was already installed on the forge server, maybe something is not wired up correctly or we have to add our $PATH somehow.
