### ISSUE TITLE
Issue Using Named Routes

### ISSUE THREAD

**Issue by daugaard47** [beyondcode/expose#150]
When I use Named routes with Expose like this:
```
Route::get('/contact', 'ContactController@index')->name('contact');
```
This link `<a href="{{ route('contact') }}">` takes me to `https//mysite.test/contact` rather `https://mysite.sharedwithexpose.com/contact`

If the link looked like this:
`<a href="/contact">` it works correctly and I get the URL  `https://mysite.sharedwithexpose.com/contact`

I'm using this command to start Expose:
```
 expose share https://mysite.test --subdomain=mysite
```

I tried changing the `APP_URL`  in the `.env` file to `https://mysite.sharedwithexpose.com` but that didn't solve the route issue either.

With NGROK I get the FORWARD URL `https://046cc3444xxxxx.ngrok.io -> http://mysite.test:80`
Then all my named routes work: 
```
Route::get('/contact', 'ContactController@index')->name('contact');
---
<a href="{{ route('contact') }}">
Returns: https://046cc3444xxxxx.ngrok.io/contact
```

How can I achieve this same behavior with Expose?

Should note that I'm on Windows 10 and using Laragon.

**Comment by TechTailor** [comment]
Would second this. If anyone has a way to make named routes work in exposed env, please share. Thanks in advance.

-TT

**Comment by daugaard47** [comment]
> URL::forceRootUrl("http://mysub.sharedwithexpose.com");

That worked great. Nice job @TechTailor !!! Thank you for figuring that out. I appreciate it.
