### ISSUE TITLE
Any plans to add support for XDEBUG or only port forwarding?

### ISSUE THREAD

**Issue by suchal** [beyondcode/expose#157]
I must say, great work everybody! I just started using this tool and I'm loving it. Although there were two things which I am missing a lot. If there are any plans to implement them, I am available to contribute.

1. The expose command creates it's own HTTP server instead of using Port forwarding from the already running server (apache/nginx/valet) 

So the xdebug that I've installed doesn't seem to work on it. If we had port forwarding support, we could use our local apache/nginx to serve the site and still use xdebug

2. I heavily use laravel websockets and I want to use expose for tunneling the WSS 

Please let me know what can be done and how I can help. Thanks!

**Comment by mpociot** [comment]
Port forwarding will be added in v2 of Expose (it's already available in the master branch if you want to host your own server)
Tunnelling Websocket connections should work as expected
