### ISSUE TITLE
Token not showing in dashboard 

### ISSUE THREAD

**Issue by babojamo** [beyondcode/expose#158]
Nothing shown in dasboard for auth token
![image](https://user-images.githubusercontent.com/17305760/98513552-00996a80-22a3-11eb-811b-76668ba8d3f0.png)
https://beyondco.de/licenses/expose

**Comment by StevieDC** [comment]
Same thing for me I'm afraid

**Comment by ChristianPavilonis** [comment]
Same here.

**Comment by egorzot** [comment]
the same, wtf :(

**Comment by tibidev7** [comment]
same ..
