### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by pardmeister** [beyondcode/expose#160]
I'm running Laravel valet and have been using expose for a while, but recently I've been getting 502 Bad Gateway responses. Any idea how to troubleshoot or solve this?

**Comment by GregShanken** [comment]
Might be related to this.

https://github.com/beyondcode/expose/issues/64#issuecomment-731465469

**Comment by pardmeister** [comment]
Hi Greg

Thanks for the feedback, will keep an eye on #64
