### ISSUE TITLE
Exposed localhost stuck loading

### ISSUE THREAD

**Issue by marwalsch** [beyondcode/expose#161]
I'm exposing a .NET Core 3.14 project running on IIS express. 

`expose share https://localhost:44332/ --subdomain=mySubDomain`

the registry is successful and calling the page results in an entry in the dashboard/console.

However, there seems to be no actual response occurring, calling the site through the browser just results in a seemingly infinite loading icon in the browser tab.
```
+--------+--------+----------+---------------------+----------+
| Method | URI    | Response | Time                | Duration |
+--------+--------+----------+---------------------+----------+
| GET    | /files |          | 2020-11-20 09:43:56 | 4ms      |
| GET    | /files |          | 2020-11-20 09:40:12 | 223503ms |
| GET    | /      |          | 2020-11-20 09:38:49 | 307309ms |
+--------+--------+----------+---------------------+----------+
```
Not the absurd duration for the latter calls. The dashboard lacks a response as well.

![image](https://user-images.githubusercontent.com/72074423/99785587-a2c81680-2b1d-11eb-8005-bb6e72e139d2.png)

Am I missing some configuration or something else? So far I tried: 

- running `expose https://localhost:44332/ --subdomain=mySubDomain` in different variations (no subdomain, leaving out `share ` keyword)
- running through regular http; I suspected the IIS SSL being the problem but it works completely fine with ngrok.

**Comment by FixYourSelf1** [comment]
Hey I'm having same issue, did you find a solution yet?

**Comment by marwalsch** [comment]
@FixYourSelf1 No, I assume the service is down atm.

**Comment by joshuadegier** [comment]
I'm experiencing the same, might be worth mentioning I'm running expose on a custom domain. My installation is also up-to-date (v1.4.1).

The tunnel is being setup, the dashboard is working and it does register each "hit". However, no response is being served back to the page which ends up begin blank after about 30 seconds. End result is a 504 Gateway Time-out.

**Comment by ingoldsby** [comment]
Having the same issue but getting 502 Bad Gateway after timeout

**Comment by wouterdorgelo** [comment]
Same issue

**Comment by MHassanSaqib** [comment]
same issue,, any solution?

**Comment by marwalsch** [comment]
For those still looking for a 'solution', ngrok seems to be the only comparable service that's still working atm. I suggest switching to it if generated domains are an option for you.

**Comment by wouterdorgelo** [comment]
Fixed it.. Run: `expose share 127.0.0.1:8000` (or any other local ip)

**Comment by marwalsch** [comment]
@wouterdorgelo Still doen't work for me as of today.

**Comment by rrr3da** [comment]
Any update on this? @wouterdorgelo your workaround doesn't make any effect on our server

**Comment by mpociot** [comment]
I _think_ this issue was introduced when the DNS setting got removed from the HttpClient in Expose. This means that incoming HTTP requests hit your local application, but the Expose client is unable to actually reach the shared site.

Since the latest version, you can configure your DNS server that Expose should use to resolve your shared site: https://github.com/beyondcode/expose/blob/1.0/config/expose.php#L32-L42

**Comment by joshuadegier** [comment]
I've tried upgrading expose using `composer global update beyondcode/expose` and then adding the dns line to `~/.expose/config.php` but it still serves me a blank page that loads until it serves a 504.

**Comment by ldaspt** [comment]
On my side with expose 2.6.2, it is fixed by putting the DNS option at an empty value

```
expose --server-host=xxx --auth=xxxxxxxxxxxxx --subdomain=xxxx --dns=  share http://xxxxx
```
