### ISSUE TITLE
docker run expose publish - config not written

### ISSUE THREAD

**Issue by voarsh2** [beyondcode/expose#162]
I'm on Ubutbu and ran docker run expose publish.

I see:
Published expose configuration file to: /root/.expose/config.php

But it doesn't exist.

**Comment by MeestorX** [comment]
I have the same issue.

**Comment by icawebdesign** [comment]
It gets written inside the docker container.

If you run this for example:

```docker run -t -v ${PWD}:/root/.expose expose publish```

You should find the expose `config.php` file gets written to your current dir.
