### ISSUE TITLE
How to get expose MY-AUTH-TOKEN?

### ISSUE THREAD

**Issue by senthur1994** [beyondcode/expose#167]
I checked the document [https://beyondco.de/docs/expose/getting-started/sharing-your-first-site#authenticating-with-sharedwithexposecom](url). But here they didn't mentioned about generating token step so it's very difficult to identify how to generate token. So anyone know how to generate token then add it here and document will good.

**Comment by gsmofgsm** [comment]
And the error message doesn't really help.
```
Authentication failed. Please check your authentication token and try again.

You can obtain your free authentication token at https://beyondco.de/login - or host your own server.
The Expose documentation can be found at https://beyondco.de/docs/expose

Connection to server closed.
```

**Comment by gsmofgsm** [comment]
I found it out!
You login at https://beyondco.de/login, and click the expose pannel (get started). Then you will see your access token there.
In your local project, run
```
expose token <your token>
```
Up and running :-)

**Comment by senthur1994** [comment]
> I found it out!
> You login at https://beyondco.de/login, and click on the expose pannel the get for free button(a little bit misleading I would say :-P). Then you will see your access token there.
> In your local project, run
> 
> ```
> expose token <your token>
> ```
> 
> Up and running :-)

Thanks man !!!!

**Comment by kfvit-andreaskviby** [comment]
![image](https://user-images.githubusercontent.com/47242730/110778023-1a9f8580-8262-11eb-8be4-5378aba0b461.png)

Where is it?
