### ISSUE TITLE
TLS handshake failed (windows)

### ISSUE THREAD

**Issue by mortenscheel** [beyondcode/expose#17]
The expose command fails on Windows 10 with this message:

```
Could not connect to the server.
Connection to sharedwithexpose.com:443 failed during TLS handshake: Unable to complete TLS handshake: SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
```

**Comment by ctwillie** [comment]
Do you have your CA bundle file configured in php.ini? Could be causing the error.

**Comment by ahaneef29** [comment]
I still I couldn't run in Windows 10

Expose Version : 1.2.2

> Could not connect to the server.
> Connection to sharedwithexpose.com:443 failed during TLS handshake: Unable to complete TLS handshake: SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed.

I'm using Laragon to serve my website.
[](https://laragon.org/)

**Comment by mortenscheel** [comment]
Thank @ctwillie and sorry for the late reply.

That was indeed the problem, and now it works.

@ahaneef29 I'm also using Laragon, and it was an easy fix.
The php.ini already has this line: `curl.cainfo = "path\to\laragon\etc\ssl\cacert.pem"`
All you have to is to do is to uncomment the `openssl.cafile` line and add the same path there:
`openssl.cafile="path\to\laragon\etc\ssl\cacert.pem"`

**Comment by ctwillie** [comment]
@mortenscheel Sweet! Glad you got it working.
