### ISSUE TITLE
How can I update the home page?

### ISSUE THREAD

**Issue by hcancelik** [beyondcode/expose#170]
I've updated the home page per documentation here https://beyondco.de/docs/expose/extending-the-server/custom-views#homepage however I still cannot get the updated home page. I restarted the server but that didn't help. Is there anything else that I need to do?

**Comment by ghostzero** [comment]
Remember you need to clone and start the server from your local repository. I got this done by the follwing steps:

* Clone the project and checkout the version you want to edit.
* Edit the file `resources/views/homepage.twig`.
* Start the server by running the command in the root directory of your project: `php expose serve ...` (eg. `php expose serve example.com --port=80`) (do not use the global expose command).

**Comment by hcancelik** [comment]
@ghostzero Thanks. My mistake was running the expose command under builds folder instead of `php expose`. Problem solved now.
