### ISSUE TITLE
New Tag Please

### ISSUE THREAD

**Issue by jonnywilliamson** [beyondcode/expose#178]
@mpociot Would there be any chance of a new tag on this? Installing 1.4.1 still flags up the deprecated phar-updater dependency. Thank you!

![image](https://user-images.githubusercontent.com/2513663/104621128-aa242000-5687-11eb-8f54-3239c7849794.png)

**Comment by mpociot** [comment]
I released 1.5.0 earlier today

**Comment by jonnywilliamson** [comment]
https://giphy.com/gifs/xULW8jvwhvl6BD0ig8

**Comment by jonnywilliamson** [comment]
Thank you
