### ISSUE TITLE
[Question] Automatically update .env with generated domain?

### ISSUE THREAD

**Issue by Iamscaredofcode** [beyondcode/expose#179]
Is it somehow possible to automatically update the .env with the generated subdomain e.g:

APP_URL={the generated subdomain}

or is it possible to detect if the current site is exposed/shared like:

configs/app.php:

return [
    'url' => $isExposed ? 'some.url' : 'another.url',
];

Thank you!

**Comment by marcreichel** [comment]
@Iamscaredofcode Some kind of hack/workaround (when you are using Laravel):

Add the following in your `app/Providers/AppServiceProvider.php` inside the `boot` method:

```php
public function boot()
{
    // ...
    if (app()->environment('local')) {
        config(['app.url' => request()->getSchemeAndHttpHost()]);
    }
}
```

This way you can run the app either via your local url or via the shared expose url and all urls get generated correctly.

Hope this helps.

**Comment by Iamscaredofcode** [comment]
Ok thank you! I will try that.
