### ISSUE TITLE
504 Timeout when trying to open expose.mydomain.com/users

### ISSUE THREAD

**Issue by goellner** [beyondcode/expose#18]
server is running on Laravel Forge.
php 7.3

expose.mydomain.com, /sites and /settings is working, but when clicking the users tab, there is a 504 timeout and a generic nginx error page.

**Comment by mpociot** [comment]
Can you try modifying the `database` configuration key?
Also, try and see if the database file exists. 

When clicking the user link, expose is trying to connect to the SQLite database.

**Comment by filipac** [comment]
@mpociot so it seems that running expose from supervisor is having this problem and it does not seem to load the right configuration file (i deleted a comma from ~/.expose/config.php to check if startup fails). When running ```/usr/bin/php /home/forge/.composer/vendor/bin/expose serve``` from forge user it works as expected, it even fails if i delete that comma (loads the ~/.expose/config.php file). Any idea why supervisor might be broken? Here is my config:

```[program:expose]
directory=/home/forge
command=/usr/bin/php /home/forge/.composer/vendor/bin/expose serve local.filipac.net
numprocs=1
autostart=true
autorestart=true
user=forge
```

**Comment by filipac** [comment]
I did try to change database key from config and work when running manually, but when running in supervisor the config is ignored.

**Comment by filipac** [comment]
There is no way to specify the config file as a CLI argument or --option right?

**Comment by filipac** [comment]
What worked for me now: ```ln -s .expose/config.php .expose.php``` in /home/forge as that is the working directory for supervisord

**Comment by goellner** [comment]
Can confirm, that when running with supervisord it is not working, but when starting it directly everything works as expected. I also had to change my startup command to `command=/usr/bin/php /home/forge/.composer/vendor/bin/expose serve mydomain.com`

**Comment by dasraab** [comment]
same problem here. also changed my supervisor command like @goellner did. running without supervisor works ...

**Comment by ahmedash95** [comment]
I was able to solve this through these steps

1 - `$COMPOSER/vendor/beyondcode/expose/condig/expose.php` to home directory `/home/forge/.expose.php` 

2 - open the file and change database to a custom path 
```php
'database' => '/home/forge/expose-db/expose.db',
```

3 - run `expose serve`

4 - /users should work for you as **expose** should be able to create db file

**Comment by goellner** [comment]
ended up using PM2 (https://pm2.keymetrics.io/) and everything worked right away. I created this file: `/home/forge/.expose.php`

**Comment by AbdelElrafa** [comment]
@goellner Can you add in some steps on how to solve it and set it up using pm2?

**Comment by edalzell** [comment]
> ended up using PM2 (https://pm2.keymetrics.io/) and everything worked right away. I created this file: `/home/forge/.expose.php`

@goellner can you share how you set it up on Forge?

**Comment by ahmedash95** [comment]
> @ahmedash95 can you share how you set it up on Forge?

I'll write an article once I solve my last error but here is a quick recipe

First, create an empty repo then create a site from this repo. once you do that ssh to your forge server and find the nginx config for that domain and change it's content to be like that https://beyondco.de/docs/expose/server/ssl . and just replace the `/location` part as Forge taking care of all other stuff

ssh to your forge server and install require expose globally 

```
composer global require beyondcode/expose
```

then you copy the config file to home directory

```
 cp /home/forge/.config/composer/vendor/beyondcode/expose/config/expose.php /home/forge/.expose.php
```

modify the database path at`.expose.php` like below

```
'database' => '/home/forge/expose-db/expose.db',
```

also 

then run expose serve and make sure users tab is working 
![image](https://user-images.githubusercontent.com/8272048/85107876-f0f38980-b20e-11ea-838e-7c4bfcf4e796.png)

Now everything should be fine apart from this bug I've right here
https://github.com/beyondcode/expose/issues/31

**Comment by edalzell** [comment]
Run it how? Via a daemon or manually?

**Comment by ahmedash95** [comment]
> Run it how? Via a daemon or manually?

as you want. can be manually like
```
/home/forge/.config/composer/vendor/bin/expose serve share.yourdomain.com --port 8085
```

or daemon using forge. but make sure to set the path to home directory
![image](https://user-images.githubusercontent.com/8272048/85136053-53647e00-b23f-11ea-894a-279e5f98a9b8.png)

**Comment by SamuelNitsche** [comment]
> > Run it how? Via a daemon or manually?
> 
> as you want. can be manually like
> 
> ```
> /home/forge/.config/composer/vendor/bin/expose serve share.yourdomain.com --port 8085
> ```
> 
> or daemon using forge. but make sure to set the path to home directory
> ![image](https://user-images.githubusercontent.com/8272048/85136053-53647e00-b23f-11ea-894a-279e5f98a9b8.png)

Yep, that works. Thank you!

**Comment by ahmedash95** [comment]
Happy to help!

**Comment by edalzell** [comment]
Hero status for @ahmedash95

**Comment by edalzell** [comment]
I still cannot get it to work, how frustrating. I have installed it locally in my Forge site: (`composer require...`).

<img width="758" alt="Laravel Forge | dl-sites 2020-06-19 07-34-39" src="https://user-images.githubusercontent.com/6069653/85144021-6d7e6c00-b1ff-11ea-9554-7bd98f3f2bac.png">

I have this in `/home/forge`: 
<img width="569" alt="image" src="https://user-images.githubusercontent.com/6069653/85144080-838c2c80-b1ff-11ea-8ec8-501c2a4876c7.png">

And it is reading the config file (I had a typo in there the first time and got an error).

I have this in my nginx conf:
```
    location / {
        proxy_pass             http://127.0.0.1:8080;
        proxy_read_timeout     60;
        proxy_connect_timeout  60;
        proxy_redirect         off;

        # Allow the use of websockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
```

I have SSL on w/ wildcards:
<img width="935" alt="image" src="https://user-images.githubusercontent.com/6069653/85144248-c5b56e00-b1ff-11ea-8596-8778f08d8690.png">

When I go to my expose url I get 
<img width="717" alt="image" src="https://user-images.githubusercontent.com/6069653/85144318-dc5bc500-b1ff-11ea-9f71-3981aa06ad69.png">

But I can't get to the admin page nor any share, even though the share seems to work.
<img width="360" alt="image" src="https://user-images.githubusercontent.com/6069653/85144406-f8f7fd00-b1ff-11ea-9a03-8aed04b94c21.png">

Lastly my config:
```
    'admin' => [
        'database' => '/home/forge/.expose/expose.db',
        'subdomain' => 'admin',
```

So, what silly thing did I miss?

**Comment by ahmedash95** [comment]
@edalzell can you make sure the server's nginx config file has `.` as prefix of server name
![image](https://user-images.githubusercontent.com/8272048/85145038-49954780-b24c-11ea-89dd-0983575d341a.png)

that way we are telling nginx to redirect any `subdomain.(your expose domain)` to expose so you can get the response

**Comment by edalzell** [comment]
Turns out it was a DNS issue, I forgot to add the wildcard DNS entry. @ahmedash95's instructions went perfect

**Comment by goellner** [comment]
Just to add to @edalzell comment, if someone has the same problem:

You have to have a wildcard A record in your DNS settings:

*.mydomain.com -> 123.123.123.123 (your server ip)

**Comment by enzolarosa** [comment]
I solve the issue following the @ahmedash95 instructions

thank you
