### ISSUE TITLE
am i doing something wrong?

### ISSUE THREAD

**Issue by jigsaw678** [beyondcode/expose#183]
```
─(odin㉿kali)-[~/expose]
└─$ ./expose publish                                                  127 ⨯ 1 ⚙
PHP Warning:  require(/home/odin/expose/../../autoload.php): failed to open stream: No such file or directory in /home/odin/expose/expose on line 20
PHP Fatal error:  require(): Failed opening required '/home/odin/expose/../../autoload.php' (include_path='.:/usr/share/php') in /home/odin/expose/expose on line 20
```
i have installed composer

**Comment by mpociot** [comment]
It seems like you have not installed Expose globally via composer, but just cloned the Expose repository - and forgot to install its composer dependencies.

Either install Expose by running `composer global require beyondcode/expose`, or use your local copy and run `composer install` to get the latest dependencies.
I would prefer the global installation though.
