### ISSUE TITLE
PHP 8.0 Working But Thrown ReactPHP Error.

### ISSUE THREAD

**Issue by dennisong45** [beyondcode/expose#184]
`
Feb 05 17:44:27 ip-127.0.0.1 php[24299]: #1 phar:///home/ubuntu/.composer/vendor/beyondcode/expose/builds/expose/vendor/clue/ndjson-react/src/Decoder.php(131): Evenement\EventEmitter->emit()

Feb 05 17:44:27 ip-127.0.0.1 php[24299]: #2 phar:///home/ubuntu/.composer/vendor/beyondcode/expose/builds/expose/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Clue\React\NDJson\Decoder->handleData()

Feb 05 17:44:27 ip-127.0.0.1 php[24299]: #3 phar:///home/ubuntu/.composer/vendor/beyondcode/expose/builds/expose/vendor/react/stream/src/ReadableResourceStream.php(146): Evenement\EventEmitter->emit()

Feb 05 17:44:27 ip-127.0.0.1  php[24299]: #4 
phar:///home/ubuntu/.composer/vendor/beyondcode/expose/builds/expose/vendor/react/event-loop/src/StreamSelectLoop.php(245): React\Stream\ReadableResourceStream->handleData()

Feb 05 17:44:27 ip-127.0.0.1 php[24299]: #5 phar:///home/ubuntu/.composer/vendor/beyondcode/expose/builds/expose/vendor/react/event-loop/src/StreamSelectLoop.php(212): React\EventLoop\StreamSelectLoop->waitForStreamActivity()

Feb 05 17:44:27 ip-127.0.0.1  php[24299]: #6 phar:///home/ubuntu/.composer/vendor/beyondcode/expose/builds/expose/vendor/clue/reactphp-sqlite/src/functions.php(216): React\EventLoop\StreamSelectLoop->run()

Feb 05 17:44:27 ip-172-31-25-254 php[24299]: #7 phar:///home/ubuntu/.composer/vendor/beyondcode/expose/builds/expose/expose(25): Clue\React\SQLite\runWorker()
Feb 05 17:44:27 ip-127.0.0.1 php[24299]: #8 /home/ubuntu/.composer/vendor/beyondcode/expose/builds/expose(14): require('...')
`

Composer Version 1.6.3
Beyondcode Verion 1.50
PHP 8.0.1 (cli)

**Comment by mpociot** [comment]
Do you still see this error with the latest version? I'm unable to reproduce this error locally with PHP 8.
