### ISSUE TITLE
[Feature Request] Option to change URL format to http(s)://<expose/ fixed string>.TLDomain:<port>/<random/selected subdomain>/

### ISSUE THREAD

**Issue by rahulraj80** [beyondcode/expose#185]
Hi Marcel  @mpociot / Team Members,

Thanks for an awesome tool. This works very well. 👍🏼👍🏼👍🏼👍🏼

I have been going through the code to see if the URL format for server/client can be modified:
From -> 
```
http(s)://<random/selected subdomain>.TLDomain:<port>/
(e.g. http://asdc23sfwr.someserver.net:8080/)
```
To ->
```
http(s)://<expose/ fixed subdomain>.TLDomain:<port>/<random/selected string>/
(e.g. http://exposesubdomain.someserver.net:8080/asdc23sfwr/)
```
The benefit of this that I can think of:

For people in the apache environment (no nginx), setting up certbot/letsencrypt based SSL would become trivial as there is no wild card requirement. 

Also, apache configuration for virtual hosts will become much simpler and crisp.

My rudimentary understanding of how the code works indicates that this has linkages in multiple locations. 

1. Is there some way to do it already that I have missed in the documentation?
2. Is it easy / relatively simple for this to be done by a beginner (looking at myself)?
3. Can someone guide me on how to do it, if it is not too much trouble, or at least indicate where all I should be making changes?
4. If someone smarter than me believes that this is useful for the community at large and is willing to create a patch/fork, I would be forever grateful! 🙏🏼🙏🏼

Thanks and Cheers!!
Rahul

PS: This is NOT an issue, I am not sure how to change the label.

**Comment by mpociot** [comment]
Hi Rahul,

the proposed feature is currently not possible due to the way that the expose URLs get detected, by parsing the subdomain.
I don't see us adding this feature. Feel free to fork. this package to add it yourself, if you really need this option.

**Comment by rahulraj80** [comment]
Thanks for the feedback. I partially agree with your view that not many people will need it and so it does not make sense for you to implement it.

I will relook at the code and see how I can modify it on a fork.
However, if you could still share some guidance on how the project is structured or which files / functions I need to start with, that would be very helpful.

Cheers and thanks!
Rahul
________________________________
