### ISSUE TITLE
Missing space on the console output

### ISSUE THREAD

**Issue by AlexMartinFR** [beyondcode/expose#186]
Just wanted to notify you of a missing space on the console output.
Just between 🖥  &  "**Desktop apps with Electron**":

<img width="576" alt="Capture d’écran 2021-02-10 à 18 24 55" src="https://user-images.githubusercontent.com/19224681/107547204-7cba8b80-6bcd-11eb-8d85-ea7aedb509bb.png">

I wanted to submit a PR but couldn't find that text in the project.

**Comment by mpociot** [comment]
Thanks for reporting this :D
