### ISSUE TITLE
TCP port sharing

### ISSUE THREAD

**Issue by MeestorX** [beyondcode/expose#188]
Anyone able to get TCP port sharing working?

**Comment by MeestorX** [comment]
:-(

**Comment by mpociot** [comment]
If you want, ping me on Telegram @mpociot and I'll help you set this up. It might take some time before it ends up on the public server 🙂

**Comment by MeestorX** [comment]
@mpociot Wow! Thank you so much. So I don't waste your time, let me make sure it's still set up in Docker and ready to test. (I'm lost in docker too, but that's a different problem)

**Comment by MeestorX** [comment]
@mpociot Thank you again. I've sent you a note, but it's likely quite late where you are. I included my e-mail if that's better for you. Cheers!

**Comment by MeestorX** [comment]
Just checking that you received my ping on telegram, @mpociot ?

**Comment by luvncoco** [comment]
any clue ?

**Comment by MeestorX** [comment]
Anyone else ever gotten this to work?

**Comment by MeestorX** [comment]
Well, it's been a few months, and I see a lot of activity here. 
Is it possible now to do tcp port forwarding with a server hosted on a vps?

**Comment by luvncoco** [comment]
i think @mpociot is working on the release, he replied me on telegram after 2-3 month ahahaha
