### ISSUE TITLE
POST requests result in 540 Gateway-timeout

### ISSUE THREAD

**Issue by schmidfelix** [beyondcode/expose#189]
When sharing my local site to `sharedwithexpose.com` everything works. But when I try to fill out any form (e.g. the login form) which executes a POST request, the site loads for a long while (10 minutes) and then times out:

![CleanShot 2021-02-17 at 08 50 28](https://user-images.githubusercontent.com/22103266/108172489-35685980-70fd-11eb-9f6a-22b52824b54d.png)

That's what I see in my expose dashboard:
![CleanShot 2021-02-17 at 08 51 02](https://user-images.githubusercontent.com/22103266/108172563-4749fc80-70fd-11eb-88d0-27a0e53cfe58.png)

**Comment by mpociot** [comment]
Does it matter which kind of POST data you send? Could it be that the POST payload is too large?
I haven't experienced this before.

**Comment by schmidfelix** [comment]
No, I can't imagine that. I'm just sending the normal Laravel Jetstream login form containing my email and password. I've tried in multiple projects and it haven't worked anywhere 🤷‍♂️

**Comment by schmidfelix** [comment]
I've tried to debug the problem further, and after setting some breakpoints with xdebug everything started working again without touching any code.. lol

**Comment by smartinec** [comment]
Any further troubleshooting tips? I'm having the same issue where POSTs never return.

**Comment by schmidfelix** [comment]
I was using a non-released version back then, somehow composer installed the "dev-main" branch as version which lead to this bug. After updating to the latest stable version everything worked again

**Comment by smartinec** [comment]
I’m using “sail share” on Laravel 8. So, it’s launching a docker container and exposing the docker host. Ngrok works fine. I’ve noticed Laravel generating fully qualified URLs instead of relative ones, so maybe it’s related to that.

**Comment by schmidfelix** [comment]
Hm, I haven't worked with Laravel Sail or Docker. I'm afraid I cant help you with that. Maybe just open a new issue?
