### ISSUE TITLE
Expose working with Laravel Socialite

### ISSUE THREAD

**Issue by JonPurvis** [beyondcode/expose#191]
Is this possible?

I have my app accessible via Expose but because I'm using the Socialite package (specifically the Google Driver) to handle logging in, it then redirects to the `redirect_uri` I set when creating doing the Socialite set up. 

The only solution I can think of is always making sure the subdomain is the same, and then adding that to the list of allowed URL's in Google.

Just wondered if I'm missing something really obvious!

Thanks

**Comment by mpociot** [comment]
Hey,

yeah that's definitely possible. I'm using Expose in combination with the GitHub Socialite login - so I don't know how the Google one is configured, but if your redirect_uri is the one from Expose, I wouldn't see why it shouldn't work.
