### ISSUE TITLE
Does this actually work?

### ISSUE THREAD

**Issue by MeestorX** [beyondcode/expose#193]
Seriously. 
I would love to know if this can actually do tcp tunnelling (as advertised).
Since nobody is volunteering to explain how to make it work, it’d be worth it to me to pay someone, that is, if anyone here has been able to made it work. 
So, if you know how to do it and would like to make a few bucks, please message me!
Thanks!

**Comment by mpociot** [comment]
TCP Tunneling is working on the master branch, which is for the upcoming version 2.
That means that TCP tunneling is also not yet available on the free sharedwithexpose.com server - which is running the latest stable version of 1.x

**Comment by MeestorX** [comment]
Thank your reply, but I don't understand what you're saying.
It's working? It's not working?
To be even more clear, I don't care about the sharedwithexpose server. I just want to have this hosted on my own server and share tcp tunnels. So far nobody has been able to tell me how to do this. I've tried everything I can think of to make this work, and have failed each time.
You graciously offered to help, but I guess you changed your mind? :(
