### ISSUE TITLE
Warning: Phar::mapPhar

### ISSUE THREAD

**Issue by devscript-abdo** [beyondcode/expose#194]
PHP Warning:  Phar::mapPhar(C:\Users\username\AppData\Roaming\Composer\vendor\bin\expose(21) : eval()'d code): failed to open stream: No such file or directory in C:\Users\username\AppData\Roaming\Composer\vendor\bin\expose(21) : eval()'d code on line 9

WINDOWS 10 
PHP 7.4
XAMPP SERVER
COMPOSER last version

**Comment by mpociot** [comment]
It looks like something's wrong with your composer installation or the Expose installation. Please make sure that Expose is correctly installed on your system.
