### ISSUE TITLE
Nested/wildcard subdomain support?

### ISSUE THREAD

**Issue by itambek-godaddy** [beyondcode/expose#195]
Would it be possible to support nested/wildcard domains?

Here's what I mean:

`expose mysite`

Would ensure that all these below would work:

* `mysite.sharedwithexpose.com`
* `foo.mysite.sharedwithexpose.com`
* `bar.mysite.sharedwithexpose.com`

This would be immensely helpful for subdomain-based multi-tenancy sites on Laravel.

**Comment by mpociot** [comment]
That's a cool feature idea - I'll need to see how that can be implemented on our free service. We currently use a wildcard LetsEncrypt certificate, which doesn't allow wildcard subdomains.

So this really has two parts that need to be done:

1. When sharing a site, the Expose server needs to forward subdomain requests to a shared subdomain back to the connected client
2. Figure out how we can use LetsEncrypt along with this (or maybe buy a wildcard SSL certificate - not sure if that works for wildcard sub-subdomains)

**Comment by itambek-godaddy** [comment]
Even being able to support this when running our own servers would be great :)

**Comment by mpociot** [comment]
This will be possible when using v2 and a custom subdomain/domain

**Comment by denizaygundev** [comment]
@mpociot could you share how this is possible please? I've got Expose Pro and can't see anything in the docs
