### ISSUE TITLE
Add MAX_CONNECTION_RETRIES config in config.php

### ISSUE THREAD

**Issue by dennisong45** [beyondcode/expose#196]
By default,
protected const MAX_CONNECTION_RETRIES = 3;

Is there a way to change it from config.php?

It seems the API Delete, nor ADMIN disconnect and 'maximum_connection_length' => 1, is redundant. It keeps reset every time I kill it from my expose server.

**Comment by mpociot** [comment]
I'd accept a PR that makes this value configurable.
