### ISSUE TITLE
PHP 7.2 and function trailing commas

### ISSUE THREAD

**Issue by timrspratt** [beyondcode/expose#20]
Hey,

The composer.json specifies PHP 7.2.5 as the minimum requirement, but there are PHP 7.3 formatting rules being applied, which result in errors (see below). I can update my version pf PHP no issue, just putting this here as others may not be able to and could run into these issues.

![image](https://user-images.githubusercontent.com/20431294/84915332-8e867600-b0b4-11ea-86dd-611aa38f5e2e.png)

https://github.com/beyondcode/expose/blob/master/app/Server/Factory.php#L212

**Comment by ahinkle** [comment]
https://github.com/beyondcode/expose/blob/baa9819daf68b2e279bf05c4487008b374b53cd3/composer.json#L21

**Comment by timrspratt** [comment]
The minimum PHP version solves this, so closing, thanks
