### ISSUE TITLE
Dashboard Websocket Connection Fails

### ISSUE THREAD

**Issue by Hornet-Wing** [beyondcode/expose#202]
I am having issues with the websocket connection on the dashboard which means that new requests don't automatically appear unless I refresh the page.

When I load the Dashboard I get:
```
GET ws://localhost:4041/socket
[HTTP/1.1 404 Not Found 4ms]

Firefox can’t establish a connection to the server at ws://localhost:4041/socket.
localhost:4041:42:24
```

I have tried various combinations of OS (Windows and Linux), Browsers (Chrome and Firefox) as well as Expose servers (my own and beyondcode's). I'm out of ideas on how I can debug this issue. Has anyone else come across this?

Thanks!

**Comment by mpociot** [comment]
Yeah this is an issue when sharing multiple sites at the same time. 
The expose client is currently always sending the realtime data to the first dashboard port (4040) instead of the correct one. 
Would be cool to see a PR for this 🙂

**Comment by Hornet-Wing** [comment]
Thanks for the reply Marcel.

I havent been able to get even one instance of expose to push the logs. Am I missing some local php module or config?

**Comment by ivannggnnavi** [comment]
Hwh3j

**Comment by sschlein** [comment]
Closing this issue because it's old. Please feel free to open a new one if it's still relevant.
