### ISSUE TITLE
Shared site suddenly disconnects

### ISSUE THREAD

**Issue by SabatinoMasala** [beyondcode/expose#204]
After sharing the site for a couple of hours, it sometimes happens that my expose server is no longer listing the client site under 'shared sites'.
The client however still thinks it's connected, so the client is stuck in an unreachable state untill you restart the `expose share` command (or supervisor).

I cannot reproduce this issue in a stable way, however I believe its root cause is with the internet connection of the client.

**Comment by SabatinoMasala** [comment]
After further investigation I found a reproducible approach to this issue:
- Connect a client device using ethernet
- Share a site on this client
- **block** the client from internet access, but keep the ethernet cable in (and keep the device reachable on local network)
- The server will disconnect the client, but the client will keep its connection alive (or at least think it does)
- Unblock the client from internet access
- The client is left in an unreachable state, the server won't reconnect and the client won't notice it got disconnected

**Comment by dragonfire1119** [comment]
I'm having this problem as well. Used the sharedwithexpose server & my own same problem.

**Comment by MetalArend** [comment]
Glad this has already been reported. I'm not really sure how I can provide some more information that would be helpful.

**Comment by sohaibilyas** [comment]
having same problem:

- expose share website.test
- it's connected 
- disconnect wifi on your computer/laptop
- expose client is still connected just like ngrok client
- enable wifi and expose connection is dropped on the expose server not on client, ngrok reconnects after connection loss

**Comment by sschlein** [comment]
Closing this issue because it's old. Please feel free to open a new one if it's still relevant.
