### ISSUE TITLE
Gateway timeout

### ISSUE THREAD

**Issue by bertog** [beyondcode/expose#205]
Hi there,

Since this morning I have this issue lauching the **expose** command:

Could not connect to the server.
HTTP/1.1 504 Gateway Time-out
Server: nginx
Date: Tue, 04 May 2021 05:28:24 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 160
Connection: keep-alive

```
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

I have no clue ... Any suggestion?

Guido

**Comment by mpociot** [comment]
Thanks for reporting this. Looks like some server hiccups. 
Should be fine now

**Comment by nbalkandzhiyski** [comment]
I had the same issue from time to time. 
It happened again today a few times

![image](https://github.com/beyondcode/expose/assets/80831490/269a878f-a2e6-4c70-aad7-1d6962248091)


Is there any status page or anywhere we can report issues whenever they happen? 
I'm using the Expose almost all the time and this gets confusing when you need it, even if you use the pro plan
