### ISSUE TITLE
Use with Shopify App Proxy redirects to root domain

### ISSUE THREAD

**Issue by liamjcooper** [beyondcode/expose#206]
Hi, not sure if Shopify is doing something funky here but I'll try and explain this issue as best I can.

I am using Expose to tunnel my local machine for a project where I am developing a Shopify application. One of the features in the Shopify Partners dashboard is the ability to "proxy" requests from any shop frontend that has my app installed through a specified prefix. My app can handle these requests and securely check whether the request actually comes from the shop via a signature. [More info here.](https://shopify.dev/tutorials/display-dynamic-store-data-with-app-proxies)

My setup is like so:
Proxy: /apps/[app-name]
To: https://[subdomain].sharedwithexpose.com/[path]

To test it I tried to access an available route on my app through a test Shopify store App Proxy but it redirected to the beyondcode docs rather than my app: "https://beyondco.de/docs/expose" which then redirected to "https://beyondco.de/docs/expose/introduction". Similar behaviour to when you just access the root domain "sharedwithexpose.com". In the console and the dashboard for the running Expose tunnel, there are no logged hits, just sits there idle.

This is the following response from Shopify when you hit the proxy:
<img width="592" alt="Screenshot 2021-05-06 at 14 42 16" src="https://user-images.githubusercontent.com/17281410/117308241-43668480-ae79-11eb-9c7f-e967cd4cf693.png">

No Location header, just a meta refresh trick to the corresponding URL.

However, when I try this with ngrok which is tunneling the same vhost, using the ngrok domain ([subdomain].ngrok.io) works as expected and proxies through to my app. I don't know if Shopify is doing something specifically for ngrok URLs or if Expose is expecting something else?

I didn't know where to express my issue, so I thought I'd start here.

**Comment by mpociot** [comment]
Are you sure that you hit the correct proxy URL?

**Comment by liamjcooper** [comment]
Yeah, pretty certain. I just tried it with a randomly generated URL, tunneling through to a locally running PHP development server (`php -S localhost:8080`) which is serving a plain index.html file - I changed the proxy URL to match the generated URL and when I go to the Shopify proxy URL it still redirects. Here is the page I get when I hit that proxy URL directly in the browser:
![Shopify App Proxy/Expose page](https://i.imgur.com/qCf9WTB.png)

This is the App Proxy page for the app, showing part of the URL that was generated by Expose:
![Shopify App Proxy page](https://i.imgur.com/e4hujWi.png)

**Comment by mpociot** [comment]
Could you show me what's going on in the internal Expose dashboard on port 4040?
There you should see some incoming requests.

**Comment by liamjcooper** [comment]
This is the bit I don't get - no hits. The only hit that's in the dashboard is the one where I tested the tunnel was up and working beforehand. 

![Expose dashboard](https://imgur.com/rQSF9hl.png)

Please note a different Expose URL, I stopped the server after I replied so I generated a new tunnel. I changed the URL again in the App Proxy setup to reflect this and did try it again but no luck.

**Comment by mpociot** [comment]
Okay that's very weird. Seems like Shopify is not accessing the proxy correctly?

If you want, ping me on Telegram to investigate further so you don't have to redact screenshots on GitHub. My Telegram username is mpociot

**Comment by mpociot** [comment]
Just a follow up: I managed to fix this issue in Expose 👍
