### ISSUE TITLE
Share https site with non-standard local port

### ISSUE THREAD

**Issue by tpetry** [beyondcode/expose#208]
I am maintaining an application which is built to __only__ support https, when trying to share the application working locally on a non-standard port expose is ignoring the specific port and will use 443 which is used by a different application:

```
expose share https://myapp.test:8443
Thank you for using Expose!

---
Local-URL:		myapp.test:443:8443
Dashboard-URL:		http://127.0.0.1:4040
Expose-URL:		https://w8lw6u5g5j.sharedwithexpose.com
```

The internal logic to decide whether to use http/https and which port is currently very restricted. When the url is prefixed with `https://` then the port 443 will be forced. And later on depending on the port https transport is only used when the port is 443.

**Comment by mpociot** [comment]
You can just share the site without using any protocol at all:

`expose share myapp.test:8443`

**Comment by tpetry** [comment]
This does not work. If the `https://` prefix is not provided, expose assumes the url to be a http endpoint. When using the sharedwithexpose.com url you will then get a `Client sent an HTTP request to an HTTPS server.` error.
