### ISSUE TITLE
"Could not connect to the server"

### ISSUE THREAD

**Issue by MrMooky** [beyondcode/expose#213]
I just wanted to give this a try on my M1 Mac mini but received the following message:

```
Could not connect to the server.
Connection to sharedwithexpose.com:443 failed during DNS lookup: fwrite(): Send of 38 bytes failed with errno=65 No route to host
```

I set the token but when calling `expose` from my app directory I get the above message. Any idea how to fix this?

**Comment by mpociot** [comment]
Maybe the expose server was down at that time? I am unable to reproduce the error locally.

**Comment by MrMooky** [comment]
Still get the same error. No expose for me then.

<img width="663" alt="Screenshot 2021-06-08 at 13 16 43" src="https://user-images.githubusercontent.com/3603346/121175816-cbb2bd80-c85b-11eb-95c5-930b6a9d972b.png">

**Comment by mpociot** [comment]
Could you try changing your local DNS to `1.1.1.1` and see if the error still persists?
There seems to be a DNS related issue: #231

**Comment by MrMooky** [comment]
That worked, thanks. :)
