### ISSUE TITLE
How to keep Expose Server alive on Windows

### ISSUE THREAD

**Issue by bastianhilton** [beyondcode/expose#223]
I have read the documentation here: https://beyondco.de/docs/expose/server/starting-the-server

How to keep it alive via Mac OS and Linux but there aren't ways to keep it alive on Windows. Normally you could easily do it if Expose was an application or a some sort of file, but since its commands i'm curious of how to do that on windows.

The current documentation works for windows except the part to keep Expose alive just in case the command prompt is exited.

Any help would be greatly appreciated.

**Comment by mpociot** [comment]
Sorry, I don't have any experience in hosting your own Expose server on Windows.
If you (or anyone else) has any experience with this and can help improve the documentation, I would appreciate a PR.
