### ISSUE TITLE
docker run expose  ErrorException     Undefined property: stdClass::$server_host

### ISSUE THREAD

**Issue by mrsemad** [beyondcode/expose#224]
Hello.
i've run expose in docker container with `docker run -v $PWD/expose-config.php:/src/config/expose.php expose share 127.0.0.1,` i had token issue and i fixe it with -v $PWD/expose-config.php:/src/config/expose.php.
but i have Error Exception. `ErrorException     Undefined property: stdClass::$server_host`
The complete Error:
` ErrorException 

  Undefined property: stdClass::$server_host

  at app/Client/Client.php:110
    106▕                 });
    107▕ 
    108▕                 $connection->on('authenticated', function ($data) use ($deferred, $sharedUrl) {
    109▕                     $httpProtocol = $this->configuration->port() === 443 ? 'https' : 'http';
  ➜ 110▕                     $host = $data->server_host;
    111▕ 
    112▕                     $this->logger->info($data->message);
    113▕                     $this->logger->info("Local-URL:\t\t{$sharedUrl}");
    114▕                     $this->logger->info("Dashboard-URL:\t\thttp://127.0.0.1:".config()->get('expose.dashboard_port'));

  1   app/Client/Client.php:110
      Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined property: stdClass::$server_host", "/src/app/Client/Client.php", [Object(stdClass), Object(React\Promise\Deferred), "127.0.0.1", "https"])

      +1 vendor frames 
  3   app/Client/Connections/ControlConnection.php:37
      App\Client\Connections\ControlConnection::emit("authenticated")`

**Comment by mpociot** [comment]
You are using the master branch, which is already using v2 of the server. Please use version 1 until 2.x is deployed to all servers.
