### ISSUE TITLE
Timezone change option

### ISSUE THREAD

**Issue by thatal** [beyondcode/expose#225]
First of thank your for your **expose** it helps me a lot during development. I just wanted ask that if there will be timezone change option it will helps. Currently it showing different timezone.

**Comment by mpociot** [comment]
Expose is not modifying the timezone of your local application- how do you parse the timezone?

**Comment by thatal** [comment]
My log and system time are showing different thats why I was asking to change timezone. have a look at the screenshot.

![screenshot expose](https://user-images.githubusercontent.com/17490342/121175269-7f29ab00-c878-11eb-84db-429f0ac558eb.jpg)
 showing different ones.
