### ISSUE TITLE
Can't specify port for sharing

### ISSUE THREAD

**Issue by fredericseiler** [beyondcode/expose#23]
```bash
$ expose share https://mysite.test:3000 --subdomain=mysite
Thank you for using expose.
Local-URL:		mysite.test:443:3000
```
As you can see, the specified port `:3000` is replaced by `:443:3000`.

Is there a way to force the port when using the https sharing format ?

**Comment by fredericseiler** [comment]
```bash
$ expose share https://mysite.test:3000 --subdomain=mysite
Thank you for using expose.
Local-URL:		mysite.test:443:3000
```
As you can see, the specified port `:3000` is replaced by `:443:3000`.

Is there a way to force the port when using the https sharing format ?

**Comment by mpociot** [comment]
You can share the site without specifying "https://" - expose then assumes it's running on port 443.

```
expose share mysite.test:3000 --subdomain=mysite
```

**Comment by fredericseiler** [comment]
Actually, if I don't specify "https://", expose uses http anyway. (As you said [there](https://github.com/beyondcode/expose/issues/13#issuecomment-645336957) ?)
