### ISSUE TITLE
--subdomain does not work with docker run expose

### ISSUE THREAD

**Issue by mrsemad** [beyondcode/expose#232]
using expose 1.0 on docker. i run docker images with `docker run -v $PWD/expose-config.php:/src/config/expose.php expose share 127.0.0.1 --subdomain=test`  but the option --subdomain does not work.
the output: 
`Thank you for using Expose!

---
Local-URL:		127.0.0.1
Dashboard-URL:		http://127.0.0.1:4040
Expose-URL:		https://jypj15wkty.sharedwithexpose.com
`

**Comment by sschlein** [comment]
Closing this issue because it's old. Please feel free to open a new one if it's still relevant.
