### ISSUE TITLE
--subdomain option does not work with basic expose command

### ISSUE THREAD

**Issue by mrsemad** [beyondcode/expose#233]
after installing expose on Ubuntu 18.04 and running `expose share 127.0.0.1 --subdomain="test"`.
The option --subdomain doesn't working.
`Thank you for using Expose!

Local-URL:		127.0.0.1
Dashboard-URL:		http://127.0.0.1:4040
Expose-URL:		https://m0nuwof8ls.sharedwithexpose.com
`
Is that a bug !!

**Comment by sschlein** [comment]
Closing this issue because it's old. Please feel free to open a new one if it's still relevant.
