### ISSUE TITLE
How to stop?

### ISSUE THREAD

**Issue by PeraMika** [beyondcode/expose#240]
Once when I run `expose` - how can I stop it? 
`CTRL+C` doesn't stop it. 
**Documentation** doesn't mention anything about stopping: https://expose.beyondco.de/docs 

----------------

Currently I'm using PHP 7.3.11 on Windows 7 64 bit (Git Bash), I didn't test on other OS...

**Comment by colbyalbo** [comment]
+1 
Wondering the same thing

**Comment by sschlein** [comment]
I hope that you have been able to stop it since the issue was created

**Comment by kokoshneta** [comment]
Why was this issue closed as ‘completed’ when no answer or solution was provided? Ctrl+C still does not stop the Expose process.

The only way I have found to stop sharing a site is to log on to the online dashboard on the Expose website, navigate to _Active Tunnels_ and click the little trash icon next to the tunnel you want to close.

That does not seem like an obvious or reasonable way to stop a terminal process to me…
