### ISSUE TITLE
padraic/phar-updater is abandoned

### ISSUE THREAD

**Issue by timrspratt** [beyondcode/expose#248]
Just upgraded to v2 which uses `padraic/phar-updater` as a dependency. It's an abandoned package. Are you confident this is a safe decision moving forward to use a package that is no longer maintained? Would it be worth forking it (if anything to remove the composer warning!)

**Comment by mpociot** [comment]
This is still the recommended way to add auto-updating capabilities to a Laravel Zero application according to their docs. So unless this gets forked by Laravel Zero, I'll stick with it to keep the ability to update the PHAR file itself.
