### ISSUE TITLE
[2.0.1] x-exposed-by value wrong

### ISSUE THREAD

**Issue by PhilETaylor** [beyondcode/expose#249]
`expose -V` gives `Expose 2.0.1`

So I run `expose share http://127.0.0.1`

Then I visit the dashboard at http://127.0.0.1:4040 

Then I make a requires to the Expose-Url from another tab

I would expect the value of `x-exposed-by` to be `2.0.1`

What I see is `x-exposed-by Expose 2.0.0-beta`:

<img width="985" alt="Screenshot 2021-06-22 at 10 30 03" src="https://user-images.githubusercontent.com/400092/122900765-e0578100-d344-11eb-8d79-a52f001142e9.png">

**Comment by mpociot** [comment]
Yeah, that value is coming from the server, which is still running `2.0.0` (which had the wrong version number)

**Comment by PhilETaylor** [comment]
ah that makes sense then, thanks.
