### ISSUE TITLE
[2.0.1] You are not allowed to specify custom subdomains

### ISSUE THREAD

**Issue by PhilETaylor** [beyondcode/expose#250]
`expose share http://127.0.0.1` gives:

<img width="1321" alt="Screenshot 2021-06-22 at 10 33 25" src="https://user-images.githubusercontent.com/400092/122901262-4b08bc80-d345-11eb-931c-ab87107724fa.png">

Note that it "thinks" that `http` is a custom domain... its not, its the protocol of the local site to share (as per the documentation)

**Comment by PhilETaylor** [comment]
`expose share http://localhost:3000` from the [documentation](https://expose.dev/docs/getting-started/sharing-your-first-site) gives:

```
Trying to use custom domain: httplocalhost
```

which is obviously wrong too :)

**Comment by mpociot** [comment]
Right, we should try and strip the protocol, if present to generate the automatic slug: https://github.com/beyondcode/expose/blob/master/app/Commands/ShareCommand.php#L41-L42
