### ISSUE TITLE
Custom domain on Expose Pro not working

### ISSUE THREAD

**Issue by timrspratt** [beyondcode/expose#255]
I've registered a custom domain on my account:

![image](https://user-images.githubusercontent.com/20431294/122938914-10197f80-d36b-11eb-8480-46395fc8acc6.png)

I've then ran the command to make this default:

```
expose default-domain tim.aero.dev --server=eu-1
```

However, when I run `expose` I get:

![image](https://user-images.githubusercontent.com/20431294/122939056-30e1d500-d36b-11eb-8b3f-a21e76042af4.png)

**Comment by timrspratt** [comment]
Update: running `expose --server=eu-1` works, however, this I thought was the default server and so was not required to be set?

**Comment by mpociot** [comment]
Did you configure the correct expose token from your dashboard?

**Comment by timrspratt** [comment]
Update number 2: I typed `expose default-server eu-1` and turns out that's a command too 😂.

Now that the server and domain are set in the config, running `expose` works fine 😊 

The wording on the site: `# Set default domain + server` implies the server would be set too. I guess this could either be fixed to apply the server too, or this guide changed to run the 2 commands (although 2 commands feels too loose)

**Comment by mpociot** [comment]
Hmm...it should work though:

https://github.com/beyondcode/expose/blob/master/app/Commands/SetDefaultDomainCommand.php#L19

I'll see what's causing this bug, as it should work exactly as you tried to use it :)
But glad that it works now 👍

**Comment by mpociot** [comment]
Ahh, I think I know what went wrong.
Did you migrate from Expose 1 @timrspratt? In this case the config file did not yet have the default_server key, which the command does not yet add. I'll fix this

**Comment by timrspratt** [comment]
I think it might be this: https://github.com/beyondcode/expose/blob/3dd01488951bd9c9f97cc7c4c74aec50560fa75a/app/Client/Support/DefaultServerNodeVisitor.php#L21

Should it not be looking for `default_domain`?

**Comment by timrspratt** [comment]
And yes. I migrated from v1

**Comment by grantholle** [comment]
I'm having this problem as well. I've set the "default domain" as per the instructions.

However, it doesn't do it by default.

```
➜ expose share invoicing.test
Trying to use custom domain: invoicing

You are not allowed to use this custom domain.
```

Adding the `--server` flag as suggest doesn't use my custom domain:

```
➜ expose share invoicing.test --server=us-2
Trying to use custom domain: invoicing

Status:                 Expose Pro 💎
Local-URL:		invoicing.test
Dashboard-URL:		http://127.0.0.1:4040
Expose-URL:		http://invoicing.us-2.sharedwithexpose.com:443
Expose-URL:		https://invoicing.us-2.sharedwithexpose.com
```

I have to do the full command:

```
➜ expose share invoicing.test --domain=expose.archboard.dev --server=us-2
Trying to use custom domain: invoicing

Status:                 Expose Pro 💎
Local-URL:		invoicing.test
Dashboard-URL:		http://127.0.0.1:4040
Expose-URL:		http://invoicing.expose.archboard.dev:443
Expose-URL:		https://invoicing.expose.archboard.dev
```

However, when I try to visit my custom domain, `https://invoicing.expose.archboard.dev`, I get redirected to is `https://invoicing.us-2.sharedwithexpose.com` and an error message of "The tunnel "invoicing" was not found on this Expose server."
