### ISSUE TITLE
Expose users interface in dashboard not working

### ISSUE THREAD

**Issue by danielrusu** [beyondcode/expose#257]
Hello, 

It seems that users interface in expose server dashboard is not working. I am not used with laravel and everything I tried to debug the application does not give any result.

**Comment by beebmx** [comment]
I have the same issue.
The `Shared sites`, `TCP connections` and `Settings` views are working, but the `Users` view looks broken.

**Comment by danielrusu** [comment]
> I have the same issue.
> The `Shared sites`, `TCP connections` and `Settings` views are working, but the `Users` view looks broken.
I mange to make it work. I had to create and configure path to expose.db and after I shared a site it worked.

**Comment by AlexVanderbist** [comment]
Hi! Make sure there is a sqlite database file configured and that the file actually exists.

If you're using the default Expose config, it should be in `~/.expose/expose.db`. If that file doesn't exist, you can create it using `touch ~/.expose/expose.db`.

**Comment by donmbelembe** [comment]
Hello @AlexVanderbist  Still not working

**Comment by terion-name** [comment]
same here

**Comment by sschlein** [comment]
Closing this issue because it's old. Please feel free to open a new one if it's still relevant.
