### ISSUE TITLE
TCP Tunnelling only available on Pro?

### ISSUE THREAD

**Issue by MeestorX** [beyondcode/expose#259]
Since TCP Tunnelling was only just enabled in v2, I would like to try it out without having to sign up, just to see if it works, but it seems that it's only enabled for Pro subscriptions.

Is there a time-limited trial or something I can do to test this out before signing up or building my own server version?

**Comment by mpociot** [comment]
Hi,

it's been a while since you opened this issue, but we now have a 14 day Expose Pro trial that you can activate after logging in on https://expose.dev :)
