### ISSUE TITLE
Storing token, receiving Undefined index: HOME

### ISSUE THREAD

**Issue by Braunson** [beyondcode/expose#26]
Running Windows 10, PHP 7.4.2 and installed expose globally. Grabbed a token, and ran:

`expose token XXXXX` with my token, and got this response:

```
Setting the expose authentication token to "xxxxx-xxxx-xxxx-xxxx-xxxxxxxxx"

In StoreAuthenticationTokenCommand.php line 27:

  Undefined index: HOME
```

**Comment by sohaibilyas** [comment]
try using gitbash terminal or wsl

**Comment by Braunson** [comment]
@sohaibilyas Thanks, used Git CMD and it ran without issue.

**Comment by abhiburk** [comment]
I am using Windows with php7.4. I Tried using GitBash but still not working.
Even using $_SERVER['HOME'] ?? $_SERVER['USERPROFILE'] it is throwing me the same error
