### ISSUE TITLE
Specify host when using `share-port`

### ISSUE THREAD

**Issue by plabbett** [beyondcode/expose#260]
I haven't been able to find a way to specify a host when using `expose share-port`.  I think this would be a beneficial addition to the TCP sharing options. 

```bash

# Similar to ngrok
expose share-port local.test:1234

# Another suggestion
expose share-port 1234 --host=local.test

```

My particular use case is that I run multiple [Laravel Homestead in per-project installation](https://laravel.com/docs/8.x/homestead#per-project-installation) on Windows and would like to selectively target the host in addition to the port.  It also lets you proxy to other machines on your network without having to install a client on that machine directly.

**Comment by sschlein** [comment]
Closing this issue because it's old. Please feel free to open a new one if it's still relevant.
