### ISSUE TITLE
Is ( instead of { intentional?

### ISSUE THREAD

**Issue by Krisell** [beyondcode/expose#262]
https://github.com/beyondcode/expose/blob/97993318e737a422075444cfe8d180415ed43180/app/Http/RouteGenerator.php#L50

Note the left parenthesis in `{$method}-($uri}`

If the `(` is intentional, I think a comment about the asymmetry would be good, but I'm guessing it's intended to be a `{`? I'm posting this as an issue instead of a PR since I don't know the implications and how this affects tests.

**Comment by sschlein** [comment]
Closing this issue because it's old. Please feel free to open a new one if it's still relevant.
