### ISSUE TITLE
In ShareCurrentWorkingDirectoryCommand.php line 47:

### ISSUE THREAD

**Issue by chucklin72** [beyondcode/expose#265]
Upgraded to 2.0 and it broke

In ShareCurrentWorkingDirectoryCommand.php line 47:
                                
  readlink(): Invalid argument

**Comment by SudoGetBeer** [comment]
Do you use valet?
If yes check the files within ~/.config/valet/Sites
A colleague had a .DS_Store there after she deleted the file it worked.

**Comment by HadrienX** [comment]
I had the same issue until today.
Make sure to share a site which is hosted in your Valet directory if you are using Valet.
To void this error you should write `expose share yourdomain.test` instead of only `expose`
