### ISSUE TITLE
Does not work with HTTPS

### ISSUE THREAD

**Issue by kornatzky** [beyondcode/expose#272]
I have a local Homestead Laravel. In /etc/hosts I set a domain name, say www.example.com
When I try to expose it, using HTTPS, I get error messages about the assets. Saying they are loaded via HTTP while the site is HTTPS. What can I do? 
This makes Expose totally unusable on mobile. 
For desktop, I can try to use the HTTP URL that exposes gives. But on mobile it goes automatically to the HTTPS

**Comment by adamhopkinson** [comment]
I don't think this is an issue with Expose - if you were to serve your site locally using https, you'd get the same insecure assets warning in the browser.

**Comment by kornatzky** [comment]
Does it mean I should put a SSL certificate in the local environment for this to work?

**Comment by sschlein** [comment]
I've answered this via email:

If your app is at http://blabla.dev on your local machine and your tunnel is at https://blabla.sharedwithexpose.com, the assets must be loaded via the https URL and not via the local URL.
