### ISSUE TITLE
Cannot expose local sites

### ISSUE THREAD

**Issue by connecteev** [beyondcode/expose#28]
I'd like to expose my local site (running laravel on port 8000 for the backend, nuxt.js on port 3000 for the front-end) to others. How can I go about doing this?

I went through the installation and configuration steps here:
https://beyondco.de/docs/expose/getting-started/installation
https://beyondco.de/docs/expose/getting-started/sharing-your-first-site
https://beyondco.de/docs/expose/client/sharing

Then, I tried to expose just the laravel (backend) code (for now)
```
composer global require beyondcode/expose
expose token [YOUR-AUTH-TOKEN]
cd ~/Sites/my-awesome-project/
expose
```
But then https://my-awesome-project.sharedwithexpose.com does not load and gives an error: 502 Bad Gateway.

I also tried:
```
$ expose share 192.168.0.14:8000
Thank you for using Expose!
⭐️ Support us by starring the repo at https://github.com/beyondcode/expose ⭐️
---
Local-URL:		192.168.0.14:8000
Dashboard-URL:		http://127.0.0.1:4040
Expose-URL:		https://t0hb3wdq1o.sharedwithexpose.com

```
However, going to https://t0hb3wdq1o.sharedwithexpose.com doesnt load.
I see ```502 Bad Gateway```

How can I get this to work? I'd like to expose not just the laravel back-end, but also the nuxt front-end, which is supposed to communicate with the laravel back-end over APIs.

**Comment by drbyte** [comment]
Keep in mind that `502 Bad Gateway` is typically an nginx error indicating that the gateway configured for that site isn't responding: eg: PHP FPM's socket isn't found because FPM isn't running.

**Comment by connecteev** [comment]
Ok, I'm not sure what to do to fix the problem

**Comment by johnLitoBardinas** [comment]
This is also may issue, the documentation doesn't  clarify how to access the [AUTH-TOKEN] or Authentication Token it just said 

"You can obtain such a token by signing in to your Beyond Code account. If you do not yet have an account, you can sign up and create an account for free. "

here is the link:
https://beyondco.de/docs/expose/getting-started/sharing-your-first-site

**Comment by connecteev** [comment]
@johnLitoBardinas that's true, thanks for sharing the documentation link....it would be good to add to the docs but I am still not sure how to solve this problem (ie expose a local site).

**Comment by mad-ice** [comment]
Ran into this issue today as well, and after some time debugging I finally found a solution. If you're using Vagrant with Ubuntu like I do, you'll need to add your local development hostname (e.g. `my-awesome-project.test`) to `/etc/hosts` like so:

```
127.0.0.1 my-awesome-project.test
```

Hope this helps 🙂

**Comment by martyf** [comment]
I'm a MAMP Pro user, and the information above from @mad-ice solved this for me. Ensuring my local URL (which MAMP Pro writes to `/etc/hosts` along with 127.0.0.1) matches Expose made the Expose URL work flawlessly.

**Comment by Mesbahema** [comment]
@johnLitoBardinas so you know where exactly can I get the token.

**Comment by Karina-Kosenko** [comment]
> @johnLitoBardinas so you know where exactly can I get the token.

Please try this token: 7aeb1eae-4d5e-4649-b967-908fa3f25a2f
I found it here https://beyondco.de/licenses/expose and it works for me.

**Comment by zcaceres** [comment]
> > @johnLitoBardinas so you know where exactly can I get the token.
> 
> Please try this token: 7aeb1eae-4d5e-4649-b967-908fa3f25a2f
> I found it here https://beyondco.de/licenses/expose and it works for me.

This is the token for your specific account, you probably should remove it from here :-)
