### ISSUE TITLE
Expose server not accessing /users endpoint 

### ISSUE THREAD

**Issue by rverrips** [beyondcode/expose#285]
I found that when starting up "expose serve" on an Ubuntu server (provisioned using laravel forge) that the service was starting as the forge user, but not creating and using the expose.db file, so no users could be created or edited and I would get a 503 "bad gateway" from the /users endpoint in the server. 

Adding this line to **/etc/supervisor/conf.d/expose.conf** resolves the issue. 

`environment=HOME="/home/forge"`

Just thought I'd mention - Feel free to close this issue if you don't find it helpful.

**Comment by IMPMAC** [comment]
Thanks @rverrips I had this exact issue and this solve it
