### ISSUE TITLE
log all incoming payloads to a file ?

### ISSUE THREAD

**Issue by vesper8** [beyondcode/expose#287]
Hello. I have purchased a yearly license for Expose Pro and I would really like a means, or an option, to log all incoming payloads to a log file.

I currently have a local tunnel on my Mac and I want to log everything to a log file so I can examine the payloads at a later time.

Is this currently possible? If not.. could you please consider adding this feature.

Many thanks!

**Comment by sschlein** [comment]
Closing this issue because it's old. Please feel free to open a new one if it's still relevant.
