### ISSUE TITLE
Trying to use custom domain: http

### ISSUE THREAD

**Issue by okneloper** [beyondcode/expose#288]
I've just installed the newest version of expose using composer, registered on https://expose.dev/ and performed the 3 steps from the dashboard 

The third being 
```
expose share http://localhost
```

And got this error message: 
```
$ expose share http://localhost
Trying to use custom domain: http

You are not allowed to specify custom subdomains. Please upgrade to Expose Pro. Assigning a random subdomain instead.
```
The actual share seems to working though. But the above looks like a bug.

![2021-11-15_19-14-59](https://user-images.githubusercontent.com/15017593/141825186-888e8639-65f5-4b6d-93c8-d338a48e7a9f.png)

**Comment by mpociot** [comment]
Thanks, this is now fixed
