### ISSUE TITLE
UI feature requests: Section collapse  and tab bg color change

### ISSUE THREAD

**Issue by lasseeee** [beyondcode/expose#289]
Been an avid ngrok user for a long time, and Expose is a breath of fresh air, thank you! 

Some UI feature ideas:

1. The possibility to collapse the Headers section, most of the time I'm just interested in the Body, a little papercut pain to always having to scroll on a smaller laptop screen.
2. In dark mode would it be possible to switch the active/inactive tab background colors around? Darker normally imply behind and lighter in front which is the active on normally.

Real papercuts issues, a testament to how refined this package is!

**Comment by sschlein** [comment]
Closing this issue because it's old. Please feel free to open a new one if it's still relevant.
