### ISSUE TITLE
failed during TLS handshake - SSL routines:ssl3_get_record:wrong version number

### ISSUE THREAD

**Issue by connor11528** [beyondcode/expose#290]
Hi there, I am looking to get started sharing my Laravel 8 site using Expose. I normally do local development with Laravel Valet and view my site locally at `http://employbl-core.test`. After downloading the composer package globally and activating my token I went to share my site and got an error:

```shell
$ expose share http://employbl-core.test/
Trying to use custom domain: http

Could not connect to the server.
Connection to sharedwithexpose.com:443 failed during TLS handshake: Unable to complete TLS handshake: SSL operation failed with code 1. OpenSSL Error messages: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

The error persists when trying different domains of just entering `expose`. Do I have some config that's off or any ideas what's not working here?

**Comment by korey-enright** [comment]
I'm also having this issue, and am currently ¯\_(ツ)_/¯ about the possible cause. I'm getting this when I try to just curl `sharedwithexpose.com`

```
curl https://sharedwithexpose.com
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
```

so maybe there's some misconfiguration on the SSL libraries we're using? A coworker gets a successful response when curling the url, so it should work.

**Comment by haleyngonadi** [comment]
Having the same issue – Any luck?

**Comment by dillingham** [comment]
@mpociot just had this issue when upgrading to latest

**Comment by dillingham** [comment]
@mpociot 

```
Could not connect to the server.
Connection to tls://us-1.sharedwithexpose.com:443 failed during TLS handshake: SSL operation failed with code 1. OpenSSL Error messages: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

**Comment by jostromhaug** [comment]
Same here

```
Could not connect to the server.

Connection to tls://us-1.sharedwithexpose.com:443 failed during TLS handshake: SSL operation failed with code 1. 
OpenSSL Error messages: error:1408F10B:SSL routines:ssl3_get_record:wrong version number

Script expose handling the __exec_command event returned with error code 1
```

**Comment by jtomlinson** [comment]
I am seeing this issue as well. The weird thing is it worked the first time, then I stopped and started it again and now I'm seeing this error no matter what I try.

> Could not connect to the server.
Connection to tls://sharedwithexpose.com:443 failed during TLS handshake: SSL operation failed with code 1. OpenSSL Error messages: error:1408F10B:SSL routines:ssl3_get_record:wrong version number

**Comment by sschlein** [comment]
Sorry for the late reply but this should be solved and it's also related to the managed version and not an expose open source issue.
