### ISSUE TITLE
404 not found for local sites

### ISSUE THREAD

**Issue by atoaugustyn** [beyondcode/expose#299]
I have been able to install expose and but when I run expose in my Laravel projects folder and I open the URL, I get 404 - Not found

<img width="504" alt="Screenshot 2022-02-08 at 10 43 58 AM" src="https://user-images.githubusercontent.com/30342985/152971890-c5515897-769a-42a4-bf46-c5c7767b7678.png">

**Comment by kkleber1991** [comment]
What did you do to solve the problem? I'm facing the same thing.
