### ISSUE TITLE
Video Tutorials

### ISSUE THREAD

**Issue by abishekrsrikaanth** [beyondcode/expose#30]
@mpociot, First of all, thank you very much for all the great effort that you have put into this project as an alternative to ngrok. This is very helpful and exciting. 

The docs are great, but would it be possible to create a simple video tutorial on the usage of `Expose`. 

I am trying to share a Laravel Project at the root directory of the app, I get the URL, but it always ends up being a 404 error. 

It will be good to have 2 videos.
1. How to use expose with `sharedwithexpose.com` for Laravel projects
2. How to set up your own server and use expose.

Even a quick Youtube Live would be great.

**Comment by mpociot** [comment]
Yeah, good idea. I'll do that.
I'm just going to close this as it's not an "issue" :)
