### ISSUE TITLE
Unable to use custom domain

### ISSUE THREAD

**Issue by spaceemotion** [beyondcode/expose#302]
I just recently acquired Expose Pro and wanted to use my own share domain (`expose.spaceemotion.net`).

For some reason, using the Pro servers (`eu-1.sharedwithexpose.com`) works as advertised, but my own server simply runs into an error that the tunnel could not be found.

I followed the guide and verified the domain already, is there something I have missed?

**Comment by mpociot** [comment]
Hey!

Can you please get in touch with our support by sending a mail to support@beyondco.de? That's the best place to help with issues using Expose Pro 🙂
