### ISSUE TITLE
Countdown timer reverses (becomes count up) once it reached zero

### ISSUE THREAD

**Issue by michaelangelocobo** [beyondcode/expose#308]
Hi,

Countdown of remaining time becomes count up after reaching zero.
$ expose --version
Expose 2.1.2

![image](https://user-images.githubusercontent.com/680111/156533405-8eb15bef-922c-41b4-a981-bc359f248d51.png)

**Comment by mpociot** [comment]
Not really. The connection gets closed after the countdown runs out and the client automatically reconnects, giving you a new subdomain - which seems like it's going back up.

**Comment by michaelangelocobo** [comment]
Hi @mpociot,

Thank you so much for attending to this issue! Sorry if I am insisting this but I actually experienced this multiple times that's why I feel I need to file a report.

This issue happens all the time once it reaches zero. I recorded my screen as proof of the count up issue.
![sjr-sorting-is-fine-chrome-on-windows10](https://user-images.githubusercontent.com/680111/156545665-37d2934e-57cb-4eb0-95a2-30bd5d996973.gif)

Another issue connected to this is that the new suddomain is lost since it was overwritten by the new table.

Cheers,
Michael

**Comment by kamui545** [comment]
I am experiencing the same as @michaelangelocobo

To be honest, I was expecting it to automatically terminate once it reaches the limit.

Would not it be better and a more secure default behavior? I personally often forget it is running and I would rather have to restart the command (you need the new domain anyway) than having it run 24/7.
