### ISSUE TITLE
Expose appends port with proxy_redirect off

### ISSUE THREAD

**Issue by ahmedash95** [beyondcode/expose#31]
Hey Marcel. thanks for that great project. 

I'm installing Expose on Forge. it's working as expected. but for some reason it appends the `:8085` to all clients` domain

Expose Server
```
expose serve my-custom-domain.com --port 8085
```

Client
```
expose share --subdomain local.test
```
`local.test` is a valid project that works on my local through Valet

Then I get this in the dashboard - Note the port is appended
![image](https://user-images.githubusercontent.com/8272048/84940381-0a49e800-b0e0-11ea-80cb-e707079bf956.png)

And this is the `dd` of `var_dump($_SERVER)`
![image](https://user-images.githubusercontent.com/8272048/84940643-6c0a5200-b0e0-11ea-8b1b-f15202dc5dff.png)

My Nginx configuration has proxy redirect off already
```
proxy_redirect         off;
```

**Comment by fliespl** [comment]
Just realized same thing.

It also ended up: The tunnel "abc.expose" was not found on this Expose server due to this.

**Comment by sschlein** [comment]
Closing this issue because it's old
