### ISSUE TITLE
just too slow even after paying for pro

### ISSUE THREAD

**Issue by diadal** [beyondcode/expose#313]
just too slow

**Comment by mpociot** [comment]
Hey,

are you using a server that is close to your location? This should highly reduce the network overhead and improve speed.
Where are you located?

**Comment by diadal** [comment]
Nigeria but I used the free version sometime last year very fast then

**Comment by abishekrsrikaanth** [comment]
Got an AWS server in the same city as I live. Got it installed on a `t4g.small` instance on AWS. Just have one sub domain installed and it just too slow. I am on a 500mbps fiber connection. It doesn't matter. Not sure if there are any other adjustments needed to improve the speed.
