### ISSUE TITLE
Page Hangs @ https://expose.dev/feedback/1

### ISSUE THREAD

**Issue by AiFxApp** [beyondcode/expose#318]
Found an article on laravelnews- went to your site to create account. 
following the steps to create account one is directed to a 'survey' type form.. and after filling it out the "start using expose" button stay 'grayed' out after clicking and nothing happens... returning the the home page and trying to click on 'dashboard' simply redirects me back to the survey form. 

Also, cant log out? 

I would really like to test your application.. Please advise

**Comment by sschlein** [comment]
this has been removed
