### ISSUE TITLE
Website inaccesible (expose.dev)

### ISSUE THREAD

**Issue by thegamerhat** [beyondcode/expose#320]
The website is just not accessible to me, whether it's the docs or the create acount page.

![image](https://user-images.githubusercontent.com/38887390/163171283-6c451fac-a63f-45b0-898f-6d921145d574.png)

**Comment by sschlein** [comment]
Unfortunately, we had to block our managed Expose version for users in India due to excessive phishing abuse that we couldn't handle anymore. It's sad but I have no plans to get into discussions with cyber security departments of the Indian government again.
