### ISSUE TITLE
Connection to tls://eu-1.sharedwithexpose.com:443 timed out after 20 seconds (ETIMEDOUT)

### ISSUE THREAD

**Issue by zombieleet** [beyondcode/expose#325]
Hello Everyone :).

expose has been working for me for a long time up until yesterday. Today, I decided to start up expose and I keep on getting this error message

```
Could not connect to the server.
Connection to tls://eu-1.sharedwithexpose.com:443 timed out after 20 seconds (ETIMEDOUT)
```

my resolv.conf files looks like this

```
nameserver 127.0.0.11
options ndots:0
nameserver 8.8.8.8
nameserver 1.1.1.1
```

**Comment by chbrant7** [comment]
same problem for me but with this message

Could not connect to the server.
Connection to tcp://laravel-sail.site:8080 timed out after 20 seconds (ETIMEDOUT)

**Comment by jostromhaug** [comment]
Similar issue, but slightly different message

```
Could not connect to the server.

Connection to tls://us-1.sharedwithexpose.com:443 failed during TLS handshake: SSL operation failed with code 1. 
OpenSSL Error messages: error:1408F10B:SSL routines:ssl3_get_record:wrong version number

Script expose handling the __exec_command event returned with error code 1
```

**Comment by duncanmcclean** [comment]
Running into the same issue.

**Comment by philharmonie** [comment]
Any solution? Ran into the same issue running `herd share`, what uses expose under the hood.
```
Connection to tls://eu-1.sharedwithexpose.com:443 failed during TLS handshake: SSL operation failed with code 5. OpenSSL Error messages: error:80000002:system library::No such file or directory error:80000002:system library::No such file or directory error:80000002:system library::No such file or directory error:80000002:system library::No such file or directory error:0A000086:SSL routines::certificate verify failed
```

**Comment by philharmonie** [comment]
Found a solution for me:
- Follow all steps here: https://expose.dev/dashboard
- set the free server (if you don't have an pro license): `expose default-server free`
- `herd share`

**Comment by sheldonkotyk** [comment]
was working fine this morning then this evening I'm getting. 

```Could not connect to the server.
Connection to tls://us-1.sharedwithexpose.com:443 failed during TLS handshake: SSL operation failed with code 1. OpenSSL Error messages: error:0A000086:SSL routines::certificate verify failed```

**Comment by sschlein** [comment]
I am so sorry that this issue is open for such a long time but we're the worst at monitoring the open source issues of Expose, especially when it's related to other tools (i.e. Herd)

For those using Herd:
This happens if your php.ini of Herd doesn't include the correct certificate path. There was a version where this could have happened. Please check your php.ini files of Herd and look for those files:

```
curl.cainfo=/Users/seb/Library/Application Support/Herd/config/php/cacert.pem
openssl.cafile=/Users/seb/Library/Application Support/Herd/config/php/cacert.pem
```

Make sure to point them to the pem files in your users directory and everything should be good.
