### ISSUE TITLE
How to Get Basic Auth to work?

### ISSUE THREAD

**Issue by daugaard47** [beyondcode/expose#326]
I have a Pro account and I need to protect my expose link with basic auth.
When I run the following command I get an Error about not being on a pro account.

```
expose mysite.oo --auth="admin:11223344"
```

Error
> Authentication failed. This server region requires an Expose Pro license as part of our global network. Learn more at: https://expose.dev/get-pro
Connection to server closed

If I simply run `expose` I get the following:
```
------------------------------------------------------------
               Thank you for using Expose Pro
------------------------------------------------------------

Shared URL:             mysite.oo
Dashboard:              http://127.0.0.1:4040
Public HTTP:            http://mysite.us-1.sharedwithexpose.com
Public HTTPS:           https://mysite.us-1.sharedwithexpose.com
```

How can I get this working?

**Comment by sschlein** [comment]
Sorry for the late reply – the auth command seems to conflict with brower defaults and has been renamed to --basicAuth
