### ISSUE TITLE
Css is missing

### ISSUE THREAD

**Issue by daugaard47** [beyondcode/expose#33]
I'm using Expose on my local windows machine and running Laragon. Largon has ngrok support wich works fine, but limited on the requests (free plan). 

When I run `expose mysite.test` I get the following:
```
Local-URL:               mysite.test
Dashboard-URL:          http://127.0.0.1:4040
Expose-URL:             https:// mysite.sharedwithexpose.com
```

When I go to `https:// mysite.sharedwithexpose.com` the site comes up but all the CSS is missing because it's looking for the app URL which is `https://mysite.test` that's in the `.env` file.
(This happens with ngrok too.) When it happens on ngrok I go to a different page on my website and the CSS fixes itself.

When I go to a different page on my website with the Expose link it reverts back to the `mysite.test` URL.

I'm also trying to use this to do Tests with the Stripe Webhook. But always returns a `500 server error`

Is there something special I need to do to get this working with Laravel?

Any help would be appreciated.

**Side note:** If I remove `https` and use `http` the CSS comes back, but navigation links still revert back to `https//mysite.test` (Css and links work fine here)

**Comment by sebdesign** [comment]
I had a similar issue, this is how i fixed it: https://github.com/beyondcode/expose/issues/19#issuecomment-645596670

**Comment by daugaard47** [comment]
@sebdesign Thanks for the tip. Yes this fixed the CSS by doing the following:
```
 expose share https://mysite.test --subdomain=mysite
```

But if I click on a link with a Route name like this: `<a href="{{ route('contact') }}"`
```
Route::get('/contact', 'ContactController@index')->name('contact');
```
I get taken to `https//mysite.test/contact` rather `https://mysite.sharedwithexpose.com/contact`

If the link looked like this:
`<a href="/contact">` it would work. But for some reason this doesn't work: `<a href="{{ route('contact') }}"`

I tried changing the `APP_URL`  in the `.env` file to `https://mysite.sharedwithexpose.com` but that didn't solve the route issue either.

Not sure how to troubleshoot this any further.
