### ISSUE TITLE
Expose Pro no longer working / unable to update

### ISSUE THREAD

**Issue by DavidPower** [beyondcode/expose#336]
Expose was installed and running on my Windows 10 laptop like a charm.

I then created a Laravel environment using their Docker container. That all went smoothly and Laravel's working fine.

I needed to update to PHP 8+ to support Tinkerwell v3. I upgraded PHP manually, updated environment variables, rebooted, got Tinkerwell to work.

Upon updating expose to the latest version (i.e. expose self-update), I recieved the following error:

```
In Updater.php line 417:

rename(C:\Users\david\AppData\Roaming\Composer\vendor\beyondcode\expose\builds/expose.phar.temp,C:\Users\david\AppD
  ata\Roaming\Composer\vendor\beyondcode\expose\builds\expose): Access is denied (code: 5)
```

Now, expose will still run but will no longer catch hooks. It generates a 419 error.

Any idea what's going on? Anything else I can try here?

**Comment by sschlein** [comment]
Sorry for the super late reply but this has been fixed in time with a new Expose version and I am finally closing this issue.
