### ISSUE TITLE
How reset default-server for free account?

### ISSUE THREAD

**Issue by myregistration** [beyondcode/expose#337]
What options do we have for the default-server for free accounts?  I changed it to us-1 per step 3 of installation and now it does't work since I don't have a Pro account.  I tried to reset it as empty but doesn't work.  Thanks!

Update:  I found the answer at https://expose.dev/network.  You set it to free.  

`expose default-server free`

**Comment by matthewhutchings** [comment]
Please put this on the offical website - poor UX when I had to spend ages figuring this out after I accidentally ran the wrong command .

**Comment by jbnv** [comment]
And make sure that new users aren't seeing `expose default-server us-1`. It's a really bad look when a new user follows the instructions they are given and it doesn't work and they get nagware about going Pro.

**Comment by CodyPChristian** [comment]
This is still an issue, ran into it today. No mention of it on the site or CLI. Ideally shouldnt it just fall back to free if you're not pro? @mpociot @myregistration
