### ISSUE TITLE
No such server

### ISSUE THREAD

**Issue by thesunilyadav** [beyondcode/expose#345]
Hello,
I have just created account on https://expose.dev and reserved one domain `sunil.in-1.sharedwithexpose.com`
After that I followed the official guide to install the expose in system. (https://expose.dev/docs/getting-started/installation)
And Setup authentication token Then when I share the local site with `expose share http://portfolio.test` it gives some production error.

> In ServerAwareCommand.php line 105:
> No such server eu-1

![image](https://user-images.githubusercontent.com/72142357/189525566-0e8d60f3-cab5-4f65-9e4b-5ed4d55a0a3f.png)

Any guide, Please.
@beyondcode 
Thanks

**Comment by Prashank25** [comment]
I am having the same issue, the cause appears to be Cloudflare blocking our access to their server. I can access the web app through a VPN but my local running code is not using the VPN so it cannot.

**Comment by sschlein** [comment]
Yeah, unfortunately we had to shut down the service in India because it was abused a lot by phishing companies and being in contact with the Indian cybercrime department every day wasn't an option.

I am sorry that you have to rely on self hosted Expose and we can't offer the easy solution to you
