### ISSUE TITLE
Error: Could not connect to the server ... failed during TLS handshake ...

### ISSUE THREAD

**Issue by devutoo** [beyondcode/expose#346]
After creating an expose account, following the setup steps, I get the following error, when trying to expose my local site with the expose command:
`Could not connect to the server. Connection to eu-1.sharedwithexpose.com:443 failed during TLS handshake: Unable to complete TLS handshake: SSL operation failed with code 1. OpenSSL Error messages: error:14094419:SSL routines:ssl3_read_bytes:tlsv1 alert access denied.`
There are some open but unsolved issues similar to this, but maybe there is someone, who figured it out.

**Comment by caendesilva** [comment]
Having the exact same problem on Windows, however, it works in WSL.

**Comment by sschlein** [comment]
This should be solved
