### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by adelorenzo** [beyondcode/expose#36]
I ran the installation as in the documentation:
`composer global require beyondcode/expose`

then I ran the command:
`expose`

and the result was:
`expose: command not found`

What did I do wrong? I am using Ubuntu 18.04. Thank you!

**Comment by goellner** [comment]
Most likely you don't have the composer directory in your [PATH](https://askubuntu.com/questions/60218/how-to-add-a-directory-to-the-path). 

Can you try those commands: 

`echo 'export PATH="$PATH:$HOME/.composer/vendor/bin"' >> ~/.profile`

and

`source ~/.profile`

**Comment by fahim152** [comment]
Having same issue.
