### ISSUE TITLE
App version

### ISSUE THREAD

**Issue by timrspratt** [beyondcode/expose#370]
Hey @mpociot, does the app version need updating in `config/app.php`? The `master` branch says it's 2.5.0, 2.6.1 is tagged and the request header (using expose pro) says 2.3.0.

This comes from seeing the "update is available, run expose self-update" message but seemingly the version does not actually change?

<img width="480" alt="image" src="https://user-images.githubusercontent.com/20431294/222508343-2405da45-b869-46a2-8c07-9e19a3dad898.png">

**Comment by timrspratt** [comment]
When exposing, the message therefore constantly shows that an update is available
<img width="677" alt="image" src="https://user-images.githubusercontent.com/20431294/222508635-351a7641-5380-4852-8217-ab4896848522.png">

**Comment by rabol** [comment]
Same issue here

**Comment by timrspratt** [comment]
I'd happily create a PR for this but I cannot for the life of me see where the version is. The config version is `2.5.0`. Is the version something that is set when building? If so, @mpociot would you be able to quickly sort this please?

**Comment by timrspratt** [comment]
@sschlein any assistance on how to sort this please? I'm worried support for a paid for product is being ignored 😕

**Comment by mpociot** [comment]
Hey @timrspratt 
I just published a new version, that is now properly tagged as 2.6.2

Btw, if you're using Expose Pro, feel free to reach out via support(at)beyondco.de :)

**Comment by timrspratt** [comment]
Yay @mpociot thanks for sorting :) Appreciate it. Is this something you need to manually do then or can it be automated via GitHub actions?
