### ISSUE TITLE
sail share: the link only shows the key, not the full URL

### ISSUE THREAD

**Issue by Erik-Jonker** [beyondcode/expose#371]
Here is a screenshot of what happens when I run "sail share": 

<img width="352" alt="Screenshot 2023-03-06 at 13 52 21" src="https://user-images.githubusercontent.com/20435798/223102801-9bc65996-f04a-41b1-9a39-eae50ea35b8a.png">

Is it possible to give me the base URL so long? I tried appending the key to "sharedwithexpose.com" but it does not work:

<img width="1053" alt="Screenshot 2023-03-06 at 13 53 41" src="https://user-images.githubusercontent.com/20435798/223103758-c9b20a27-0aa1-4dc1-8019-d810bd2f06b4.png">

I exited the share so those links will no longer work.

**Comment by bjuppa** [comment]
Is this perhaps the same problem that was solved in https://github.com/laravel/sail/issues/545

**Comment by sschlein** [comment]
I am closing this issue because `sail share` is a different network and we can't solve this issue on our end
