### ISSUE TITLE
bug: sail share does not give a valid link

### ISSUE THREAD

**Issue by james-van-niekerk** [beyondcode/expose#373]
This is what happens when I run sail share:
<img width="696" alt="image" src="https://user-images.githubusercontent.com/60829313/223335906-b9659e6d-0416-4ce8-b7f1-410e7d59f483.png">

This is what I get when I navigate to the link provided:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/60829313/223336197-d1ddccaa-4964-4d4e-a98d-9cd6b92f90cc.png">

**Comment by dominikgeimer** [comment]
I have the same problem and http keeps spinning forever without showing anything.

**Comment by ErwanTouba** [comment]
same
