### ISSUE TITLE
Extra managed regions (e.g. Africa)

### ISSUE THREAD

**Issue by nikspyratos** [beyondcode/expose#384]
Heyo.

Is there any potential interest in adding more server regions? I don't know the underlying cloud for Expose, but I know AWS has Africa availability so it would be a nice addition.

I'm in Cape Town for example and while Expose is super handy, adding 200ms latency to every request makes things a bit laggy in the UX (especially if using something like Livewire). Going with self-hosted for now.

Other than that, just a docs/site recommendation: Only the docs mention which server regions are available on Pro, but not the main site or the upgrade page - perhaps would be nice to include a link to the docs page or include a modal that shows which regions are supported.

**Comment by sschlein** [comment]
Thanks, I have created an internal issue for this and we try to make one available soon.
