### ISSUE TITLE
Could not connect to the server. Connection to tls://us-1.sharedwithexpose.com:443 failed during TLS handshake: SSL operation failed with code 1. OpenSSL Error messages: error:1408F10B:SSL routines:ssl3_get_record:wrong version number

### ISSUE THREAD

**Issue by emincer** [beyondcode/expose#387]
Could not connect to the server.

Connection to tls://us-1.sharedwithexpose.com:443 failed during TLS handshake: SSL operation failed with code 1. OpenSSL Error messages: error:1408F10B:SSL routines:ssl3_get_record:wrong version number

This is new after Expose working flawlessly for the past week.

**Comment by theoreaves** [comment]
I am getting this following error:
herd share
Could not connect to the server.
Connection to tls://us-1.sharedwithexpose.com:443 failed during TLS handshake: SSL operation failed with code 5. OpenSSL Error messages: error:80000002:system library::No such file or directory error:80000002:system library::No such file or directory error:80000002:system library::No such file or directory error:80000002:system library::No such file or directory error:0A000086:SSL routines::certificate verify failed

I have not been able to get Expose to work yet.  Also, in Herd, DNSMasq is not running with this error:
dnsmasq: failed to create listening socket for 127.0.0.1: Address already in use

Not sure if the two are related or not.

**Comment by emincer** [comment]
Bump.

I've once again run into this issue. Anybody out there??

**Comment by snapey** [comment]
Same.  Herd reports;
```
~/Sites/dev/l10breeze  > herd share l10breeze
Could not connect to the server.
Connection to tls://eu-1.sharedwithexpose.com:443 failed: Last error for IPv4: Connection to tcp://81.99.162.48:443 failed: Network is unreachable (ENETUNREACH). Previous error for IPv6: Connection to tcp://[2a02:8801:200:1::1]:443 failed: No route to host (EHOSTUNREACH)
```

Expose (Pro) works ok
```

~/Sites/dev/l10breeze  > expose share l10breeze
------------------------------------------------------------
               Thank you for using Expose Pro
            Your pro features expire in 48 days
      Extend your license now: https://expose.dev/pro
------------------------------------------------------------

Shared URL:             l10breeze
Dashboard:              http://127.0.0.1:4040
Public HTTP:            http://l10breeze.eu-1.sharedwithexpose.com
Public HTTPS:           https://l10breeze.eu-1.sharedwithexpose.com
```

**Comment by alexgarrettsmith** [comment]
I just wrote up what solved a similar issue for me. Hope this helps.

https://github.com/beyondcode/expose/discussions/399

**Comment by sschlein** [comment]
Hey and sorry for the late reply, but this is the open source repository of the expose client and not related to Herd or the managed network directly, so please email our support for cases like this.

This is related to a missing php.ini configuration. Please check your Herd php.ini files and make sure that they include the certificate paths (with your user name)

```
curl.cainfo=/Users/seb/Library/Application Support/Herd/config/php/cacert.pem
openssl.cafile=/Users/seb/Library/Application Support/Herd/config/php/cacert.pem
```

**Comment by sschlein** [comment]
@UVLabs are the certificates in the php..ini of 8.3?

This sometimes also is an IPv6 problem, so if you would switch your Mac DNS to something like 1.1.1.1 (Cloudflare) or 8.8.8.8 (Google), it could also work. But that sounds wirds if it's only on one PHP version.
