### ISSUE TITLE
Asset URLs Contain Incorrect Port in Laravel Sail Environment with Expose Reverse Proxy

### ISSUE THREAD

**Issue by erictourigny23** [beyondcode/expose#388]
Description:
I am experiencing an issue with asset URLs in my Laravel Sail application when accessed through the Expose reverse proxy service. My application is set up to use Laravel Sail's built-in PHP development server, which runs on port 9090. However, when I access the application through Expose using the URL "eric-tourigny.us-1.sharedwithexpose.com," the asset URLs contain ":8080" in them, which causes assets to fail loading.

Expected Behavior:
Asset URLs should not contain any port information and should correctly resolve to "eric-tourigny.us-1.sharedwithexpose.com."

Steps to Reproduce:
1- Set up a Laravel Sail environment with the PHP development server running on port 9090.
2- Configure Expose to forward requests to the Laravel Sail application.
3- Access the application through the Expose URL "eric-tourigny.us-1.sharedwithexpose.com."
4- Inspect the asset URLs in the rendered HTML.

Actual Result:
Asset URLs contain ":8080," leading to asset loading issues.

Please let me know if there are any further details or logs needed to investigate this issue. Any assistance or guidance on resolving this problem would be greatly appreciated. Thank you.

**Comment by sschlein** [comment]
Sorry for the late reply but this doesn't seem like an Expose problem. Expose itself only shares the url that you share with it and does not change local paths. When using Expose, I recommend running a build version of your assets and not a development server.
