### ISSUE TITLE
Could not connect to server error:80000002

### ISSUE THREAD

**Issue by scottybo** [beyondcode/expose#391]
Hi guys,

I'm getting this error when attempting to run `herd share` or when running `expose share https://mylocalurl.test`

```
Could not connect to the server.
Connection to tls://sharedwithexpose.com:443 failed during TLS handshake: SSL operation failed with code 5. OpenSSL Error messages: error:80000002:system library::No such file or directory error:80000002:system library::No such file or directory error:80000002:system library::No such file or directory error:80000002:system library::No such file or directory error:0A000086:SSL routines::certificate verify failed
```

**Comment by kovalmatej** [comment]
> Hi guys,
> 
> I'm getting this error when attempting to run `herd share` or when running `expose share https://mylocalurl.test`
> 
> ```
> Could not connect to the server.
> Connection to tls://sharedwithexpose.com:443 failed during TLS handshake: SSL operation failed with code 5. OpenSSL Error messages: error:80000002:system library::No such file or directory error:80000002:system library::No such file or directory error:80000002:system library::No such file or directory error:80000002:system library::No such file or directory error:0A000086:SSL routines::certificate verify failed
> ```

Have you solved this?

**Comment by lhilton** [comment]
@scottybo and @kovalmatej did you ever resolve this? I'm seeing the same error.

**Comment by alexgarrettsmith** [comment]
I just wrote up what solved a similar issue for me. Hope this helps.

https://github.com/beyondcode/expose/discussions/399

**Comment by thoresuenert** [comment]
in the following blog post unter "Managing PHP settings" a few envs are written to the config files,https://beyondco.de/blog/announcing-laravel-herd 

Please check if those envs are written to your configs. That is the main cause of the problem.

**Comment by sschlein** [comment]
I am so sorry that we haven't addressed this yet but this is the open source repository of Expose and unrelated to herd or the managed Expose network.

The problem happens when the path to your certificates is wrong or missing from your php.ini. Please check your Herd php.ini and make sure that these lines (with your username!) are in there and point to the correct files:

```
curl.cainfo=/Users/seb/Library/Application Support/Herd/config/php/cacert.pem
openssl.cafile=/Users/seb/Library/Application Support/Herd/config/php/cacert.pem
```
