### ISSUE TITLE
Could not connect to the server. - 502 Bad Gateway

### ISSUE THREAD

**Issue by soltmar** [beyondcode/expose#392]
Hi there,
Today morning I've started to receive below error:
`Could not connect to the server.
HTTP/1.1 502 Bad Gateway
Server: Caddy
Date: Tue, 03 Oct 2023 08:03:24 GMT
Content-Length: 0`

It was all fine yesterday and I didn't make any changes to my localhost.
I'm not really sure if that 502 comes from my local or is it Expose issue ?
I expect it's an expose issue since my local seems to be completely fine.

**Comment by soltmar** [comment]
It seams that eu-1 server is down. us-1 works fine

**Comment by sschlein** [comment]
I am closing this because we also added EU-2 as a failover that you can use – also promising to keep an eye on these issues here in the future 🙈

If you encounter issues with the managed network by us, please send a support email so that we can investigate this quickly.
