### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by ataldev** [beyondcode/expose#396]
I get the following error while trying to share a site. I tried running the herd share command and also the expose share command. 
`Authentication failed. Please check your authentication token and try again.
Connection to server closed.`
I tried a new token as well, but it still did not work.

**Comment by jdc1898** [comment]
I am getting the same error. I even upgraded to the Pro license thinking that would get me going. No such luck...

**Comment by FikretCin** [comment]
I'm getting the same error too. Can someone support?

**Comment by chrisbalicki** [comment]
Same issue here, can't seem to get around it - have reinstalled, redone the token etc..

**Comment by ataldev** [comment]
It is working now.

**Comment by jdc1898** [comment]
It still isn't working for me. Did you do something to fix yours?

**Comment by ataldev** [comment]
I didn't do anything.
