### ISSUE TITLE
Authentication Error on Pro License

### ISSUE THREAD

**Issue by jdc1898** [beyondcode/expose#397]
I keep getting the following error:

Authentication failed. This server region requires an Expose Pro license as part of our global network. Learn more at: https://expose.dev/get-pro
Connection to server closed.

I confirmed I have a full Pro license.

**Comment by Joe-Kneeland** [comment]
me too. has been 30 mins since upgrade to pro

**Comment by jdc1898** [comment]
Any update on this?

**Comment by Joe-Kneeland** [comment]
I just tried again, same results. bummer because I need this tool right now.

**Comment by jdc1898** [comment]
> I just tried again, same results. bummer because I need this tool right now.

Same... I would love to be able use this.

**Comment by mechelon** [comment]
Hey there, this repository is for issues with the open source version of Expose - if you have problems with your Pro license, please reach out to support@beyondco.de :) (We can help you there much faster. :D)

**Comment by jdc1898** [comment]
I did and was able to have my issue resolved. 

Thank you!
