### ISSUE TITLE
[Bug]: expose command not found

### ISSUE THREAD

**Issue by Abdulfatahkb** [beyondcode/expose#401]
### System architecture

Mac, Intel (x86)

### Bug description

[Bug]: After installing the beyondcode/expose expose command cannot be found on linux
i can't call the expose executable

**Comment by ChrisLightfootWild** [comment]
It sounds like you have not set it up correctly. The [instructions](https://expose.dev/docs/getting-started/installation) show moving the expose file into `/usr/local/bin/`, so I'd double check you did that.

You can double check your path too and confirm `/usr/local/bin` is present (it should be, unless you have changed it).

```bash
echo $PATH
```
