### ISSUE TITLE
server authentication issue 

### ISSUE THREAD

**Issue by sa-clive** [beyondcode/expose#45]
Hi guys

I have followed the global composer install instructions and added it to the path on my Mac, but when I try to authenticate with the service using the expose token command I get the error in the attached screenshot:

<img width="1177" alt="Screenshot 2020-06-18 at 16 38 52" src="https://user-images.githubusercontent.com/21169158/85041720-3ddd4e80-b182-11ea-86d4-75d9eb68e40e.png">

**Comment by drbyte** [comment]
Can you share your `/Users/clive/.composer/composer.json` file contents?
Is there anything in there that doesn't need to be in "composer global"?

**Comment by sa-clive** [comment]
Please see the contents of my .composer/composer.json file

{
    "require": {
        "botman/installer": "^1.0",
        "beyondcode/expose": "^1.1"
    }
}

**Comment by choirool** [comment]
Me too

**Comment by drbyte** [comment]
@choirool what part are you saying "Me too" to? the title? the screenshot? the composer.json content? the use of a Mac? something else?

**Comment by mpociot** [comment]
It looks like you are not running expose from the distributed binary, but rather from the `expose` file that is inside of this package.
I think you added the wrong folder to your PATH environment variable. Don't add the expose dependency itself, but the composer .bin folder.

For me, this looks like this:

```
/Users/marcelpociot/.composer/vendor/bin
```

**Comment by choirool** [comment]
@drbyte I got the error like on the screenshot, but it works after changing the environment variable path to `~/.composer/vendor/bin` as @mpociot advice

**Comment by sa-clive** [comment]
Yes I can confirm that changing my path as per @mpociot suggested did the trick, thank you!
