### ISSUE TITLE
Sharing with laravel sanctum

### ISSUE THREAD

**Issue by IvanG11** [beyondcode/expose#47]
Hello, I am trying to share the project that uses laravel sanctum

I have configured sanctum with this:
SANCTUM_STATEFUL_DOMAINS = mysite.test
SESSION_DOMAIN = mysite.test

Site loads but cannot login (page 419 expired). If I change the url of SANCTUM_STATEFUL_DOMAINS and SESSION_DOMAIN with the exposure url, it works fine.

Is it possible to avoid this?

**Comment by mpociot** [comment]
I don’t think this can be done dynamically, no
