### ISSUE TITLE
Documentation request - Forge

### ISSUE THREAD

**Issue by edalzell** [beyondcode/expose#48]
Hey there, great app, thanks for building it!

I'm trying to get it set up on Forge. I can get it working (albeit not reading the published config file) until I enable SSL.

Do you have any instructions on how you're running it on Forge?

Thanks.

**Comment by edalzell** [comment]
Ideally:

- where you installed it (local to site, or in `composer global`
- what the daemon config is
- where the config file is
- what the config looks like

Thanks!

**Comment by ahinkle** [comment]
I agree -- I found some helpful tips here: https://github.com/beyondcode/expose/issues/15

**Comment by edalzell** [comment]
And here https://github.com/beyondcode/expose/issues/18#issuecomment-646485519, although I'm still having troubles.

**Comment by michellaurent** [comment]
Here's a great article about installing expose on a Forge server:

[https://medium.com/@PendoNL/installing-expose-on-a-laravel-forge-server-with-a-custom-domain-and-wildcard-ssl-d1f76a550770](https://medium.com/@PendoNL/installing-expose-on-a-laravel-forge-server-with-a-custom-domain-and-wildcard-ssl-d1f76a550770)
