### ISSUE TITLE
[Feature] Rewrite Host Header

### ISSUE THREAD

**Issue by PHLAK** [beyondcode/expose#55]
I'm unable to expose a local site available at an address other than `localhost`.

I can do the following with ngrok:

    ngrok -host-header=rewrite http://something.local:80

See: https://ngrok.com/docs#http-host-header

It would be nice to have this feature in expose.

**Comment by mpociot** [comment]
Doesn’t this solve it:

expose share something.local

**Comment by PHLAK** [comment]
Missed that, will try it out next time I'm able to.

**Comment by PHLAK** [comment]
Okay, this does appear to correctly set the `Host` header.
