### ISSUE TITLE
Wrong after using valet link 

### ISSUE THREAD

**Issue by dillingham** [beyondcode/expose#60]
I had a nested folder named ~/Sites/product/demo
`valet link product-demo.wip`
expose used `demo.wip` and 404s

**Comment by mpociot** [comment]
Yeah, right now you need to epxlicitly share product-demo.wip like this:

`expose share product-demo.wip`

It might make sense to add some kind of alias detection when sharing the current working directory, similar to how it's already done for detecting Valet TLDs:

https://github.com/beyondcode/expose/blob/master/app/Commands/ShareCurrentWorkingDirectoryCommand.php#L26

**Comment by jeop10** [comment]
I just found out about expose and I will like to try to fix it. 

If it’s ok if I try?

**Comment by ahmedash95** [comment]
Hey @jeop10 have you had anything or should I give it a try :) ?

**Comment by jeop10** [comment]
> Hey @jeop10 have you had anything or should I give it a try :) ?

Sorry I didn’t have the time, go ahead. It’s all yours
