### ISSUE TITLE
How to share my app running on docker?

### ISSUE THREAD

**Issue by silasrm** [beyondcode/expose#61]
Hi,

I'm running an laravel app on docker over local url: abc.localhost:8010 and desire to share on internet using expose. I'm trying this:
```
expose share http://abc.localhost:8010
```

My app has a subdomain routes. `abc` is a subdomain route of my app and this work fine. But expose return a timeout error: `504 Gateway Time-out`

Any idea to solve this? I'll need to add nginx config about sharedwithexpose.com subdomain?

**Comment by mpociot** [comment]
Where are you running expose? As long as you, the user that starts the expose client, can access the shared URL, you should be able to access it.

**Comment by silasrm** [comment]
I'm execute only this: `expose share http://abc.localhost:8010`

Does the person who will access need to perform the local expose as well?

**Comment by awagdy10** [comment]
@silasrm Could you please share your Dockerfile and docker-compose.yml with us?

**Comment by silasrm** [comment]
> @silasrm Could you please share your Dockerfile and docker-compose.yml with us?

version: '3'

services:
  appvoto:
    build: .
    entrypoint: dockerize -wait tcp://dbvoto:3306 -timeout 40s ./.docker/entrypoint.sh
    container_name: appvoto
    restart: unless-stopped
    tty: true
    volumes:
      - .:/var/www
    networks:
      - appvoto-network
    depends_on:
      - dbvoto
      - redisvoto

  nginxvoto:
    build: .docker/nginx
    restart: always
    tty: true
    ports:
      - "8010:80"
    volumes:
      - .:/var/www
    networks:
      - appvoto-network
    depends_on:
      - appvoto
      - echovoto

  dbvoto:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: dbvoto
    restart: always
    tty: true
    ports:
      - "33010:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - appvoto-network

  echovoto:
#    image: oanhnn/laravel-echo-server
    build: .docker/echo
    container_name: echovoto
    restart: always
    tty: true
    ports:
      - "60002:6001"
    volumes:
      - ./.docker/echo:/app
    depends_on:
      - redisvoto
      - appvoto
    networks:
      - appvoto-network

  redisvoto:
    build: .docker/redis
    container_name: redisvoto
    ports:
      - "60380:6379"
    volumes:
      - ./.docker/redis:/data
    networks:
      - appvoto-network

networks:
  appvoto-network:
    driver: bridge

**Comment by mpociot** [comment]
> I'm execute only this: `expose share http://abc.localhost:8010`
> 
> Does the person who will access need to perform the local expose as well?

No, only the client sharing the site needs that.

**Comment by silasrm** [comment]
Closed? Why?

**Comment by hailwood** [comment]
I have the same issue running my sites through Lando (a docker wrapper).

The sites get exposed via both my-site.lndo.site and a localhost url with a random port.
(*.lndo.site is a real domain that loops back to 127.0.0.1 and then there's a reverse proxy to hit the right container).

However running `expose my-site.lndo.site` or `expose http://localhost:12345` results in a 501 error when visiting.
The cli does show the request coming in, but no response.

```
+--------+-----+----------+---------------------+----------+
| Method | URI | Response | Time                | Duration |
+--------+-----+----------+---------------------+----------+
| GET    | /   |          | 2020-08-19 02:52:23 | 26ms     |
+--------+-----+----------+---------------------+----------+
```

**Comment by akalineskou** [comment]
I'm having the same issue as @hailwood 
I'm running it from a container, I see the request in the cli, but the request stalls.

The weird thing is, that if I exec in the container, and curl the address I'm sharing I get a normal response from the server.
Tried using port 80 instead of 443, but no luck.

It might be something with the binding of the server, tried using 0.0.0.0 instead of 127.0.0.1 in some of the places it's used, but again no luck.
