### ISSUE TITLE
command not found: expose

### ISSUE THREAD

**Issue by storonianskyi** [beyondcode/expose#62]
composer global require beyondcode/expose , command not found: expose

**Comment by jetrodn** [comment]
Same for me.

**Comment by MinaFaragAmin** [comment]
This solved my issue 
https://www.quicksnippets.pro/post/expose-command-not-found-on-your-mac

hope it helps.

**Comment by mpociot** [comment]
Please make sure that your composer global binary path is added to your PATH environment variable, as stated in the documentation and @MinaFaragAmin blog post 👍
