### ISSUE TITLE
escapeshellarg(): Argument exceeds the allowed length of 8192 bytes

### ISSUE THREAD

**Issue by Eldair** [beyondcode/expose#64]
Hello,

I just started using the app, testing some payment webhooks and this error occurred:
```
PHP Fatal error:  escapeshellarg(): Argument exceeds the allowed length of 8192 bytes in phar://.../Composer/vendor/beyondcode/expose/builds/expose/vendor/namshi/cuzzle/src/Formatter/CurlFormatter.php on line 137

In CurlFormatter.php line 137:
```
after which the app closed.
I'm on windows using PHP7.4

**Comment by mpociot** [comment]
Depending on the payload size that comes in this could happen.
You can increase the memory limit in your expose configuration file that you can publish with `expose publish`.

**Comment by wouter2203** [comment]
This isn't an issue with memory. `php -r "escapeshellarg(str_repeat('a', 8000));"` doesn't throw any exceptions but `php -r "escapeshellarg(str_repeat('a', 9000));"` does, regardless of the memory limit set.

A possible solution would be to check whether the `$this->rawRequest` exceeds 8000 characters and just return an empty string in `getRequestAsCurl()` if that's the case.

I wanted to try this for Github webhooks, but their payloads exceed the 8000 characters, unfortunately.

**Comment by Trashpants** [comment]
Just to throw my hat into this - I've upped my memory to 2G (tried both 2G and 2GB) and still get this issue. using ngrok no issue at all.

```
PHP Fatal error:  escapeshellarg(): Argument exceeds the allowed length of 262144 bytes in phar:///Users/nash/.composer/vendor/beyondcode/expose/builds/expose/vendor/namshi/cuzzle/src/Formatter/CurlFormatter.php on line 137

In CurlFormatter.php line 137:
                                                                         
escapeshellarg(): Argument exceeds the allowed length of 262144 bytes  
```

**Comment by Eldair** [comment]
I switched to using wsl 2 and I've set memory limit to 2GB and it works fine now (for same requests)

**Comment by Trashpants** [comment]
im really puzzled as to whats happening on my machine then - 

Just so im not being a complete idiot, this is the line I have in my config:

```
    /*
    |--------------------------------------------------------------------------
    | Maximum Allowed Memory
    |--------------------------------------------------------------------------
    |
    | The maximum memory allocated to the expose process.
    |
    */
    'memory_limit' => '1024M',

```

**Comment by dinamic** [comment]
Guys, this is still not working properly on mac OS. It does not seem to be affected by the memory limit setting.

```
    'memory_limit' => '1024M',
```

Where's this limitation coming from? I don't understand.

```
In CurlFormatter.php line 137:

  escapeshellarg(): Argument exceeds the allowed length of 262144 bytes
```

**Comment by markandrewkato** [comment]
This also happens on my mac. Checked the stack trace and it looks like an issue with the "cuzzle" package used where it fails to format large request body. 

https://github.com/namshi/cuzzle/issues/20
