### ISSUE TITLE
Unknown command expose

### ISSUE THREAD

**Issue by willsmanley** [beyondcode/expose#65]
I installed using `composer global require beyondcode/expose` and created a BeyondCode account and received an auth token for expose.

However when running `expose token xxx-xxx-xxx`, it returns `unknown command expose`.

And likewise, `which expose` returns nothing. I am on a Mac with composer v1.8.4.

**Comment by zaherg** [comment]
have you added your composer vendor bin directory to your system path?

**Comment by thomashondema** [comment]
echo 'export PATH="$PATH:$HOME/.composer/vendor/bin"' >> ~/.bashrc
replace .bashrc with .bash_profile if on mac

**Comment by willsmanley** [comment]
Thanks, got it now. For those using fish:
```
set -Ua fish_user_paths /Users/username/.composer/vendor/bin
```

**Comment by vcidst** [comment]
I'm on Ubuntu 18.04 using zsh, I found the composer paths posted above weren't valid for me. In my case, I added the following lines to `~/.zshrc` file

```
# Add Composer bin to path
export PATH="$PATH:$HOME/.config/composer/vendor/bin"
```
