### ISSUE TITLE
Problem with zsh!

### ISSUE THREAD

**Issue by princerafid01** [beyondcode/expose#70]
I am using oh my zsh on my command line. After installing expose via composer globally, when i type `expose` it says command not found. I am on linux arch. Can you help me out? 
Than you.

**Comment by mpociot** [comment]
Please make sure that you have your global composer bin path in your PATH environment variable.

See #65 #62

**Comment by antimech** [comment]
Add
`export PATH=$HOME/.config/composer/vendor/bin:$PATH`
to your
`~/.zshrc`
