### ISSUE TITLE
separate client configuration of server and domain

### ISSUE THREAD

**Issue by dakira** [beyondcode/expose#72]
This is a feature request.

It would be nice to be able to configure which host should be used to connect to the expose server and which base domain should be used to generate the links displayed client-side.

Example:

- `https://*.example.com` responds with the expose server
- `https://expose.example.com` shows the admin backend
- `https://example.com` **does not** respond with the expose server but with a webpage

An easy workaround to still use expose is setting *something*.example.com as the host. This will work and correctly set up the forward. Unfortunately the client now tells me I can connect to https://jfh347y78y.something.example.com while https://jfh347y78y.example.com would be correct. That's why optionally setting the base domain would be practical.

I can PR a solution if you like.

**Comment by MithrandirDK** [comment]
I would like this as well, hoping for a PR from you, @dakira

**Comment by MithrandirDK** [comment]
I tried looking into it myself, but must admit I am simply unable to distinguish between 
- domain
- sharedUrl
- host
- hostname
that is used throughout this application - and sometimes changing from hostname to host or vice versa through the function calls.

**Comment by dakira** [comment]
@MithrandirDK hey. I'll wait for @mpociot to comment before working in a PR.

**Comment by sschlein** [comment]
Closing this issue because it's old 🙈
