### ISSUE TITLE
Documentation Request: Expose Equivalents of ngrok commands

### ISSUE THREAD

**Issue by vcidst** [beyondcode/expose#75]
Thanks for making this!

It took me a while to realize that the equivalent of `ngrok http 3000` for expose is `expose share localhost:3000` and still I'm not sure about it. Can you add a documentation page mapping ngrok terms to expose terms and similarly for the commands? I guess it will reduce friction for anyone trying to switch

**Comment by MarvelousMari** [comment]
I'd love to write some of this, but I don't know if there are license/legal issues with directly mapping the two. Hopefully @mpociot will know!

**Comment by mpociot** [comment]
@MarvelousMari No, this will be fine. Would be cool if you could PR the documentation changes

**Comment by sschlein** [comment]
Closing this issue because it's old 🙈
