### ISSUE TITLE
Error upon instalation

### ISSUE THREAD

**Issue by imroca** [beyondcode/expose#78]
Can someone give me a hand with this?

ignacio in ~ λ composer -V
Composer version 1.10.8 2020-06-24 21:23:30

ignacio in ~ λ composer global require beyondcode/expose
Changed current directory to /Users/ignacio/.composer

  [ErrorException]
  file_get_contents(): read of 8192 bytes failed with errno=21 Is a directory

require [--dev] [--prefer-source] [--prefer-dist] [--fixed] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

<img width="1438" alt="Screen Shot 2020-06-25 at 19 39 39" src="https://user-images.githubusercontent.com/151292/85806045-fde71000-b71b-11ea-84c5-f4eabccc71c4.png">

**Comment by imroca** [comment]
hello?

**Comment by mpociot** [comment]
Is it me you’re looking for?

**Comment by mpociot** [comment]
Sorry, I have never seen this error before, but it is completely unrelated to expose as it has something to do with composer on your machine.
