### ISSUE TITLE
Cant get expose working on Server

### ISSUE THREAD

**Issue by TheLazyLemur** [beyondcode/expose#82]
running
```bash
expose serve my-domain.com
``` 
results in 

```bash
In Factory.php line 213:
                                
  syntax error, unexpected ')' 
```
php  -v shows
```bash
PHP 7.2.24-0ubuntu0.18.04.6 (cli) (built: May 26 2020 13:09:11) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.6, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by nikosdion** [comment]
According to the `composer.json` file in this repository you need PHP 7.3.0 or later. Your PHP version (7.2.24) is too old. I strongly recommend using [Ondřej Surý's PPA](https://launchpad.net/~ondrej/+archive/ubuntu/php) to install an update to date PHP version.

Note: I am not affiliated with the Expose project. I was looking through the issues to solve my own problem and I saw something easy I could help with 😄

**Comment by TheLazyLemur** [comment]
Thank you, this was the solution.

**Comment by nikosdion** [comment]
You're welcome!
