### ISSUE TITLE
No response from my tunnel at .sharedwithexpose.com

### ISSUE THREAD

**Issue by antimech** [beyondcode/expose#86]
Hello.
After I set auth token I've started expose from my project directory
`$ expose`
The local dashboard at http://127.0.0.1:4040 is working and I see some results in the requests table but the website at https://url-shortener.sharedwithexpose.com doesn't seem to respond (it keeps loading).
I've tried to disable firewall, no luck. I'm also using VPN and I tried to disable it.

I'm not sure how expose works, am I missing something?
What should I do to troubleshoot it?

Linux Mint 19.3

**Comment by antimech** [comment]
It seems like expose is not serving sites like ngrok, so I must call
`$ php artisan serve`
first, then
`$ expose share http://127.0.0.1:8000`

Now it works.

**Comment by frodeknutsen** [comment]
I'm having the same issue. Using Valet, so shouldn't have to do `artisan serve`.

**Comment by JohnnyWalkerDesign** [comment]
Valet has its own automatically tunnelling, so you don't need Expose.

     valet share

**Comment by PhilETaylor** [comment]
Ive been having issues for a while now - Expose just doesnt work at all. Well it starts up, the dashboard shows the requests, but the responses are never loaded to the browser.

```
expose -V
Expose 2.0.2

mkdir test
cd test
echo "test" >> index.html
php -S 0.0.0.0:8888
```

```
expose http://localhost:8888

./expose http://localhost:8088
Trying to use custom domain: test
You are not allowed to specify custom subdomains. Please upgrade to Expose Pro. Assigning a random subdomain instead.

Status:			Expose Free - 👉 Upgrade to Pro at https://expose.dev/get-pro
Local-URL:		test.test
Dashboard-URL:		http://127.0.0.1:4040
Expose-URL:		http://km9fyllqfw.sharedwithexpose.com:443
Expose-URL:		https://km9fyllqfw.sharedwithexpose.com

+--------+-----------+----------+---------------------+----------+
| Method | URI       | Response | Time                | Duration |
+--------+-----------+----------+---------------------+----------+
| GET    | /index.js |          | 2021-07-27 09:18:18 | 0ms      |
| GET    | /         |          | 2021-07-27 09:18:08 | 9682ms   |
+--------+-----------+----------+---------------------+----------+
```

I have not succeeded in getting a response from Expose for many months :-(
