### ISSUE TITLE
Expose mangles numeric field names in query string.

### ISSUE THREAD

**Issue by ben-morin** [beyondcode/expose#91]
index.php
`<pre><?php var_export($_GET); ?></pre>`

start php server
`sudo php -S localhost:80`

start expose
`expose share localhost --subdomain=get-test`

http://localhost/?123=1&456=2&789&foo&bar=quux
`array (
  123 => '1',
  456 => '2',
  789 => '',
  'foo' => '',
  'bar' => 'quux',
)`

https://get-test.sharedwithexpose.com/?123=1&456=2&789&foo&bar=quux
`array (
  0 => '1',
  'bar' => 'quux',
  'foo' => '',
  1 => '2',
  2 => '',
)`

**Comment by sschlein** [comment]
Closing this issue because it's old 🙈
