### ISSUE TITLE
Refused to display in a frame because it set 'X-Frame-Options' to 'sameorigin'.

### ISSUE THREAD

**Issue by NikolayBalkandzhiyski** [beyondcode/expose#94]
Hi, I'm trying to use the app with Cpriego Valet Linux, but instead of using Ngrok for testing, I'm trying to Expose.

The problem is that when I try to use Expose in Shopify app development environment the response is blocked due to 
"Refused to display in a frame because it set 'X-Frame-Options' to 'sameorigin'.", because the app is running in an iframe.

Is this problem with the expose? Is there a way I can unset the "X-Frame-Options"? I tried to find where this is coming from, but with no success.

Thanks.

**Comment by mpociot** [comment]
Does it work with ngrok? I'm not modifying the request headers / add X-Frame-Options headers anywhere, so that must come from the site that you share

**Comment by thomasmars** [comment]
@mpociot I'm having the same problem, it works with ngrok, but not with expose with the exact same setup.
These are the response headers from ngrok:
```
Cache-Control: no-cache, no-store, private
Content-Security-Policy: {removed}
Content-Type: text/html; charset=UTF-8
Date: Fri, 14 Aug 2020 11:31:20 GMT
expires: -1
pragma: no-cache
Real-Host: {subdomain2}.{subdomain1}.ngrok.io
Server: nginx/1.15.7
Transfer-Encoding: chunked
X-Powered-By: PHP/7.2.28
X-XSS-Protection: 1; mode=block
```

and these are the response headers from expose:
```
cache-control: no-cache, no-store, private
content-encoding: gzip
content-security-policy: {removed}
content-type: text/html; charset=UTF-8
date: Fri, 14 Aug 2020 11:29:32 GMT
expires: -1
pragma: no-cache
real-host: {subdomain2}.{subdomain1}.sharedwithexpose.com
server: nginx
status: 200
vary: Accept-Encoding
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-powered-by: PHP/7.2.28
x-xss-protection: 1; mode=block
x-xss-protection: 1; mode=block
```

They send the exact same response from php/laravel, with nginx in front.

**Comment by unculture** [comment]
Further to the above I have just set up nginx for SSL my expose server, and is still not sending the "X-Frame-Options" header at all. 

I think it must be being set somewhere on the way out of sharedwithexpose.com by a server in front of the expose service.

**Comment by NikolayBalkandzhiyski** [comment]
As a workaround, I'm using a Chrome extension called "Ignore X-Frame Headers", but this is not the cleanest way as this may cause some unspotted problems until the code gets uploaded to a server.

Currently, I'm still using ngrok but the static subdomains of Expose will be in great use if I can get rid of this X-Frame header.

**Comment by mpociot** [comment]
Ugh...I just figured out what's causing this issue. The reverse proxy on sharedwithexpose.com adds this header by default.
I just removed this header, so everything should be good now!

**Comment by infinitbility** [comment]
refused to display 'url' in a frame because it set 'x-frame-options' to 'sameorigin' solution

https://infinitbility.com/refused-to-display-'url'-in-a-frame-because-it-set-'x-frame-options'-to-'sameorigin'

**Comment by abishekrsrikaanth** [comment]
@mpociot do we have to do anything about this if we are self-hosting expose?
