### ISSUE TITLE
500 Internal Server Error 

### ISSUE THREAD

**Issue by ktoim** [beyondcode/expose#95]
I don't know if this is a global issue or a local issue but I wanted to make an issue as it hasn't been reported and I apologise in advance if it's a localised version.

If I visit my exposed url `{domain}.sharedwithexpose.com` it results in a 500 internal server error.

I examined my code and went to the local domain and everything seems so I went to `sharedwithexpose.com` and I can see a 500 server error on this page too.

I noticed this as there wasn't any logs coming through on either the GUI dashboard or the CLI.

**Comment by ktoim** [comment]
This seems to have been resolved now.

**Comment by carlituxman** [comment]
now I have this error, open {domain}.sharedwithexpose.com and have error 500
