### ISSUE TITLE
Sorry if I am stupid - PHP version 

### ISSUE THREAD

**Issue by boondockkid** [beyondcode/expose#96]
Super Newbie to this world I keep getting this error on my Synology NAS  Package beyondcode/expose at version  has a PHP requirement incompatible with your PHP version (5.6.11)

**Comment by Cazzar** [comment]
Per the composer.json expose requires at least PHP 7.3
https://github.com/beyondcode/expose/blob/e5b2aada2fb54d3cccf67b21214904904ee92a6b/composer.json#L21

PHP 5.6 is quite old now, as it's almost approaching 6 years since release, and has been unsupported since 2019
